Fix issues with building Legato for the local system
- Set TARGET_ARCH when building for localhost
- Supervisor looks for TARGET_ARCH and sets jail imports accordingly
- commandLineInterpreter/mkCommon.cpp correctly handles empty toolchain prefixes
- findtoolchain will work for target name if you have set the x_TOOLCHAIN_DIR
  and x_TOOLCHAIN_PREFIX correctly, even if the prefix is empty.  In particular,
  this should fix the behavior of checkpa.

Resolves: LE-8215 LE-8360
Change-Id: Ia53e8edc2e502028374a9497b616bdcbc99b9fb7

diff --git a/framework/tools/scripts/findtoolchain b/framework/tools/scripts/findtoolchain
--- a/framework/tools/scripts/findtoolchain
+++ b/framework/tools/scripts/findtoolchain
@@ -91,8 +91,18 @@ SelectToolchainDirs() {
         SelectToolchainDirs "virt_${VIRT_TARGET_ARCH}"
         ;;
     *)
-        echo "****ERROR: Unrecognized target type '$1'." >&2
-        return 1
+        local toolchain_dir_env="${target^^}_TOOLCHAIN_DIR"
+        local toolchain_prefix_env="${target^^}_TOOLCHAIN_PREFIX"
+        if [ -n "${!toolchain_prefix_env}" ]; then
+            if [ -n "${!toolchain_dir_env}" ]; then
+                TOOLCHAIN_DIRS+=("${!toolchain_dir_env}/${!toolchain_prefix_env}")
+            else
+                TOOLCHAIN_DIRS+=("${!toolchain_prefix_env}")
+            fi
+        else
+            echo "****ERROR: Unrecognized target type '$1'." >&2
+            return 1
+        fi
         ;;
 
     esac
