Legato-af updated to 16.01.2
AR7/AR86 version is SWI9X15A_07.10.00.00
WP85 version is SWI9X15Y_07.08.03.00 (or SWI9X15Y_07.08.02.00)

Change-Id: Ib2a7854c9499cdb54a4b95cc88f1b4a2b055f87b

diff --git a/framework/tools/scripts/findtoolchain b/framework/tools/scripts/findtoolchain
--- a/framework/tools/scripts/findtoolchain
+++ b/framework/tools/scripts/findtoolchain
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # Search in known locations for a cross-build tool chain.
-# The first argument is the target type (ar6, ar7, wp7, etc.)
+# The first argument is the target type (ar7, wp85, etc.)
 function PrintHelp()
 {
 cat << ENDHELP
@@ -19,11 +19,12 @@ ENDHELP
 }
 
 HOST_ARCH=$(uname -m)
+TARGET=$1
 
 # Select the appropriate list of toolchain directories to search, in order of preference
 # (most preferred first) based on the target name given.
-case "$1" in
-ar7 | wp7 | ar86)
+case "$TARGET" in
+ar7 | ar86)
     TOOLCHAIN_DIRS=(
         /opt/swi/y16-ext/sysroots/$HOST_ARCH-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi
         /opt/swi/y14-ext/tmp/sysroots/$HOST_ARCH-linux/usr/bin/armv7a-vfp-neon-poky-linux-gnueabi
@@ -32,11 +33,6 @@ ar7 | wp7 | ar86)
 wp85)
     TOOLCHAIN_DIRS=(
         /opt/swi/y17-ext/sysroots/$HOST_ARCH-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi
-        )
-    ;;
-ar6)
-    TOOLCHAIN_DIRS=(
-        /opt/poky/1.4.1/sdk/sysroots/$HOST_ARCH-pokysdk-linux/usr/bin/armv5te-poky-linux-gnueabi
         )
     ;;
 virt_arm)
@@ -65,12 +61,34 @@ help | --help | -h)
 
 esac
 
-# Go down the list until we find one that exists.
-for dir in ${TOOLCHAIN_DIRS[*]}
-do
+check_toolchain_dir() {
+    dir=$1
+
     if find $dir -name "*-linux*-gcc" > /dev/null 2>&1
     then
         echo "$dir"
+        return 0
+    fi
+
+    return 1
+}
+
+TOOLCHAIN_DIR_ENV="${TARGET^^}_TOOLCHAIN_DIR"
+TOOLCHAIN_DIR="${!TOOLCHAIN_DIR_ENV}"
+if [ -n "$TOOLCHAIN_DIR" ]
+then
+    if ! check_toolchain_dir $TOOLCHAIN_DIR; then
+        echo "Toolchain specified for target '$1' is invalid." >&2
+        exit 1
+    fi
+
+    exit 0
+fi
+
+# Go down the list until we find one that exists.
+for dir in ${TOOLCHAIN_DIRS[*]}
+do
+    if check_toolchain_dir $dir; then
         exit 0
     fi
 done
diff --git a/framework/tools/scripts/shlib b/framework/tools/scripts/shlib
--- a/framework/tools/scripts/shlib
+++ b/framework/tools/scripts/shlib
@@ -2,6 +2,8 @@
 # source this for functions only
 # Copyright (C) Sierra Wireless Inc. Use of this work is subject to license.
 
+BIN_PATH="/legato/systems/current/bin"
+
 # if SSH_PORT is defined add the port option to ssh
 SSH_PORT=${SSH_PORT:=22}
 SSH_OPTS="-p $SSH_PORT"
@@ -223,7 +225,7 @@ ScpFromTarget()
         exit 1
     fi
     ParseScpArgs $@
-    scp $SCP_OPTS $SCP_PASSED_ARGS "root@[$TARGET_IP]:$SCP_SOURCE_FILE" "$SCP_DEST_FILE" >/dev/null
+    scp $SCP_OPTS $FAST_SSH_OPTS $SCP_PASSED_ARGS "root@[$TARGET_IP]:$SCP_SOURCE_FILE" "$SCP_DEST_FILE" >/dev/null
 }
 
 ScpToTarget()
@@ -233,7 +235,7 @@ ScpToTarget()
         exit 1
     fi
     ParseScpArgs $@
-    scp $SCP_OPTS $SCP_PASSED_ARGS "$SCP_SOURCE_FILE" "root@[$TARGET_IP]:$SCP_DEST_FILE" >/dev/null
+    scp $SCP_OPTS $FAST_SSH_OPTS $SCP_PASSED_ARGS "$SCP_SOURCE_FILE" "root@[$TARGET_IP]:$SCP_DEST_FILE" >/dev/null
 }
 
 SshToTarget ()
@@ -243,7 +245,7 @@ SshToTarget ()
         exit 1
     fi
 
-    ssh $SSH_OPTS root@$TARGET_IP "$@"
+    ssh $SSH_OPTS $FAST_SSH_OPTS root@$TARGET_IP "$@"
 }
 
 # Shared (Master) ssh
@@ -258,6 +260,7 @@ StartFastSsh()
 # more checking should be done for fail of this call and see if there is a stale ControlPath
 # from a bad close, e.g.
     SSHSOCKET=~/.ssh/root@${TARGET_IP}_legato_tools
+    FAST_SSH_OPTS="-o ControlPath=$SSHSOCKET"
     ssh $SSH_OPTS -M -f -N -o ControlPath=$SSHSOCKET root@$TARGET_IP
 }
 
@@ -276,4 +279,19 @@ EndFastSsh()
 {
 #   redirect stderr to /dev/null as -q doesn't seem to work
     ssh -S $SSHSOCKET -q -O exit root@${TARGET_IP}_legato_tools 2>/dev/null
+    SSHSOCKET=""
+    FAST_SSH_OPTS=""
 }
+
+cleanup()
+{
+    exit_code=$?
+    # I could call out to a local cleanup function if it exists.
+    # For now I'll just clean up any ssh master sockets that may be lying around.
+    if [ -n "$SSHSOCKET" ]; then
+        EndFastSsh
+    fi
+    return $exit_code
+}
+
+trap cleanup EXIT
diff --git a/targetFiles/shared/bin/app b/targetFiles/shared/bin/app
--- a/targetFiles/shared/bin/app
+++ b/targetFiles/shared/bin/app
@@ -1,14 +1,6 @@
 #!/bin/sh
 
-# Starts, stops, restarts, installs and uninstalls Legato applications.
-
-LEGATO_ROOT=/opt/legato
-
-APPS_ROOT=$LEGATO_ROOT/apps
-APPS_BACKUP_ROOT=$LEGATO_ROOT/appsBackup
-APPS_SYS_CFG_BACKUP=sysCfgBack
-APPS_CFG_BACKUP=cfgBack
-SANDBOX_ROOT=/tmp/legato/sandboxes
+# Starts, stops, restarts, gets info/status, and removes Legato applications.
 
 ACTION=$1
 APP_NAME=$(basename "$2" | sed 's/\.[^.]*$//')
@@ -18,8 +10,9 @@ exitCode=0
 # used to carry the result of GetAppStatus
 appStatus="unknown"
 
-# Make sure /usr/local/bin is in the path.
-export PATH=/usr/local/bin:$PATH
+# Make sure system bin is in the path.
+# Search installed system bin first. Fallback to MTD3 if necessary.
+export PATH=/legato/systems/current/bin:/mnt/legato/system/bin:$PATH
 
 
 # Check if ps supports arguments.  If so, we need to run "ps aux" to be able
@@ -37,16 +30,12 @@ PrintUsage()
     echo "USAGE: `basename $0` [start|stop|restart|remove|status|version|info] APP_NAME [ APP_NAME ... ]"
     echo "   or: `basename $0` [start|stop|restart|remove|status|version|info] '*'"
     echo "   or: `basename $0` [list|status|info]"
-    echo "   or: `basename $0` install APP_NAME"
     echo
     echo "In the first form, names of one or more applications are given."
     echo
     echo "In the second form, all installed applications will be acted upon."
     echo
     echo "In the third form, no application names are given."
-    echo
-    echo "In the fourth form, one application name is given and the application file must be"
-    echo "provided on stdin."
     echo
 }
 
@@ -159,117 +148,36 @@ StopApp()
 }
 
 
-InstallApp()
-# Takes a single application name as its only argument.
-{
-    echo "Installing app '$1'..."
-
-    (
-        # Create the directory to install into.
-        mkdir -p "$APPS_ROOT/$1" &&
-
-        # Unpack the app into the app's install directory.
-        if ! which bsdtar > /dev/null 2>&1
-        then
-            tar xj -C "$APPS_ROOT/$1"
-        else
-            bsdtar xjop -f - -C "$APPS_ROOT/$1"
-        fi
-
-    )
-
-    if [ $? -ne 0 ]
-    then
-        rm -r "$APPS_ROOT/$1"
-        echo "Failed to unpack the application."
-        return 1
-    fi
-
-    (
-        # Fix up the permissions.
-        (
-            if ! which bsdtar > /dev/null 2>&1
-            then
-                chown -R root:root "$APPS_ROOT/$1"
-            fi
-        ) &&
-        ( find "$APPS_ROOT/$1" -type d | xargs chmod a+x-ws ) &&
-        ( find "$APPS_ROOT/$1" ! -type d | xargs chmod a-xws ) &&
-        (
-            if [ -d "$APPS_ROOT/$1/bin" ]
-            then
-                chmod -R a+x "$APPS_ROOT/$1/bin"
-            fi
-        ) &&
-
-        # Install the application's configuration into the root user's configuration tree.
-        ( appCfgInstall "$1" ) &&
-
-        # Create a user account for the app.
-        ( appUserAdd "$1" ) &&
-
-        # Set the permissions for the app.
-        ( appSetFilePermissions "$1" ) &&
-
-        # Load the latest IPC binding configuration into the Service Directory.
-        ( sdir load )
-    )
-
-    if [ $? -ne 0 ]
-    then
-        rm -r "$APPS_ROOT/$1"
-        echo "Failed to install the unpacked application"
-        return 1
-    else
-        echo "DONE"
-    fi
-}
-
-
 RemoveApp()
 # Takes a list of applications as arguments.
 {
+    # loop through the list giving each app individual treatment
+    # preserve any non-zero exit code
     while [ $# -ge 1 ]
     do
         echo "Removing app '$1'..."
 
-        rm -rf "$APPS_ROOT/$1"
+        # NOTE: update --remove will make sure the app is stopped first.
+        /legato/systems/current/bin/update --remove "$1"
 
         if [ $? -ne 0 ]
         then
             exitCode=1
-            echo "Couldn't remove installation directory."
-        fi
-
-        # In case an earlier removal process was interrupted or someone manually deleted
-        # the app's install directory, even if it doesn't look like it's installed,
-        # delete the app's configuration and user account.
-        appCfgRemove "$1"
-        if [ $? -ne 0 ]
-        then
-            exitCode=1
-            echo "Couldn't remove configuration data."
-        fi
-
-        appUserRemove "$1"
-        if [ $? -ne 0 ]
-        then
-            exitCode=1
-            echo "Couldn't remove user account."
-        fi
-
-
-        # Load the latest IPC binding configuration into the Service Directory.
-        sdir load
-        if [ $? -ne 0 ]
-        then
-            exitCode=1
-            echo "Couldn't update Service Directory's IPC bindings."
+            echo "***Error: Couldn't remove app '$1'." 1>&2
         fi
 
         shift
     done
+
+    # Load the latest IPC binding configuration into the Service Directory.
+    sdir load
+    if [ $? -ne 0 ]
+    then
+        exitCode=1
+        echo "Couldn't update Service Directory's IPC bindings."
+    fi
 }
+
 
 # Before we do any work, see if the framework is running.
 $PS | grep supervisor | grep -v grep > /dev/null
@@ -310,96 +218,11 @@ CheckAppNameAvail()
     fi
 }
 
-# Back up the specified app.  Takes a single application name as its only argument.
-BackupApp()
-{
-    appName=$1
-
-    # Delete what's in the back up app directory first.
-    RemoveBackupApp $appName
-
-    # Move the install directory of the app into the back up directory.
-    ( mv $APPS_ROOT/$appName $APPS_BACKUP_ROOT/$appName ) &&
-
-    # Back up the app's system config.
-    ( config export apps/$appName $APPS_BACKUP_ROOT/$appName/$APPS_SYS_CFG_BACKUP ) &&
-
-    # Back up the app's config.
-    config export $appName:/ $APPS_BACKUP_ROOT/$appName/$APPS_CFG_BACKUP
-
-    if [ $? -ne 0 ]
-    then
-        echo "FAILED to create back-up of app $appName"
-    fi
-}
-
-# Removes the back-up version of the specified app if it exists.  Takes a single application name as
-# its only argument.
-RemoveBackupApp()
-{
-    appName=$1
-
-    rm -fr $APPS_BACKUP_ROOT/$appName > /dev/null 2>&1
-}
-
-# Restores the back-up version of the specified app if it exists.  Takes a single application name
-# as its only argument.
-RestoreBackupApp()
-{
-    appName=$1
-
-    if [ -d "$APPS_BACKUP_ROOT/$appName" ]
-    then
-        echo "Restoring original version of app."
-
-        # Delete what's in the app directory first.
-        ( rm -rf $APPS_ROOT/$appName > /dev/null 2>&1 ) &&
-
-        # Move the install directory of the app back into the app directory.
-        ( mv $APPS_BACKUP_ROOT/$appName $APPS_ROOT/$appName ) &&
-
-        # Restore the config settings.
-        ( config import apps/$appName $APPS_ROOT/$appName/$APPS_SYS_CFG_BACKUP ) &&
-        ( config import $appName:/ $APPS_ROOT/$appName/$APPS_CFG_BACKUP ) &&
-
-        # Delete the the config backups.
-        ( rm $APPS_ROOT/$appName/$APPS_SYS_CFG_BACKUP ) &&
-        ( rm $APPS_ROOT/$appName/$APPS_CFG_BACKUP ) &&
-
-        # Create a user account for the app.
-        ( appUserAdd $appName ) &&
-
-        # Load the latest IPC binding configuration into the Service Directory.
-        ( sdir load ) &&
-
-        ( RemoveBackupApp $appName)
-    fi
-
-    if [ $? -ne 0 ]
-    then
-        echo "FAILED to restore original version of app $appName"
-        return 1
-    fi
-}
-
-
 # Check if they are asking for help.
 if [ "$1" = "-h" -o "$1" = "help" -o "$1" = "--help" ]
 then
     PrintUsage
     exit 0
-fi
-
-# Check that the application root directory exists.
-if ! [ -d "$APPS_ROOT" ]
-then
-    mkdir -p "$APPS_ROOT"
-fi
-
-# Check that the application backup root directory exists.
-if ! [ -d "$APPS_BACKUP_ROOT" ]
-then
-    mkdir -p "$APPS_BACKUP_ROOT"
 fi
 
 # Build the list of applications to operate on.
@@ -440,83 +263,10 @@ restart)
     StartApp $APP_LIST
     ;;
 
-install)
-    CheckAppNameAvail
-
-    # Only one, specific application name allowed.
-    if [ "$APP_NAME" = "*" ]
-    then
-        echo "***ERROR: One specific application name must be provided for install."
-        PrintUsage
-        exit 1
-    fi
-
-    # In case it's already installed, stop it and remove it first.
-    GetAppStatus $APP_NAME
-
-    if [[ $appStatus == "running" ]]
-    then
-        StopApp $APP_NAME
-        appStatus='stopped'
-    fi
-
-    if [[ $appStatus == "stopped" ]]
-    then
-        BackupApp $APP_NAME
-        RemoveApp $APP_NAME
-        appStatus='not_installed'
-    fi
-
-    if [[ $appStatus == "not_installed" ]]
-    then
-        InstallApp $APP_NAME
-
-        installStatus=$?
-
-        if [ $installStatus -eq 0 ]
-        then
-            RemoveBackupApp $APP_NAME
-        else
-            RestoreBackupApp $APP_NAME
-        fi
-
-        exit $installStatus
-    else
-        echo "Install $APP_NAME failed. Unknown error."
-        # in the future we may use different return codes for different errors
-        exitCode=1
-    fi
-
-    ;;
-
 remove)
     CheckAppNameAvail
-
-    # loop through the list giving each app individual treatment
-    # preserve any non-zero exit code
-    for APP_NAME in $APP_LIST
-    do
-        GetAppStatus $APP_NAME
-
-        if [[ $appStatus == "running" ]]
-        then
-            StopApp $APP_NAME
-            appStatus='stopped'
-        fi
-
-        if [[ $appStatus == "stopped" ]]
-        then
-            RemoveApp $APP_NAME
-        elif [[ $appStatus == "not_installed" ]]
-        then
-            echo "$APP_NAME is not installed. Cannot remove"
-            exitCode=1
-        else
-            echo "Remove $APP_NAME failed. Unknown error."
-            # in the future we may use different return codes for different errors
-            exitCode=1
-        fi
-    done
+    # NOTE: RemoveApp will make sure each app is stopped first.
+    RemoveApp $APP_LIST
     ;;
 
 status)
diff --git a/targetFiles/shared/bin/configEcm b/targetFiles/shared/bin/configEcm
--- a/targetFiles/shared/bin/configEcm
+++ b/targetFiles/shared/bin/configEcm
@@ -1,10 +1,8 @@
 #! /bin/sh
 
 ecm_conf=/etc/legato/ecm.conf
-usbmode=/etc/legato/usbmode
 dhcp_conf=/etc/dnsmasq.conf
 ecm_dhcp_conf=/etc/dnsmasq.ecm.conf
-legato_bringup_ecm=/mnt/flash/startup/fg_05_BringUpDeveloperInterface
 
 command_name=$(basename $0)
 usage()
@@ -28,9 +26,11 @@ cat << END_HELP
                 netmask: ipV4 netmask for the connection
 
             If no values are given the default configuration is:
-                target: 192.168.1.2
-                host: 192.168.1.3
+                target: 192.168.2.2
+                host: 192.168.2.3
                 netmask: 255.255.255.0
+
+        $command_name default - set default ecm parameters only
 
             If the given address and netmask (or the defaults if no parameters are given) conflicts
             with an existing network connection, no change will be made.
@@ -126,7 +126,6 @@ unconfig_dhcp()
 
 restart_ecm()
 {
-    host_addr=$1
     /etc/init.d/usb restart
 # we need to clean out the leases database ourselves and it seems we
 # need to delete the file completely!! Just clearing the entry doesn't work and
@@ -169,7 +168,6 @@ check_no_conflicts()
     ecm_mask=$2
 
     inet_list=$(ip -f inet addr | awk '/\d*:/,/inet/{ if (/\d*:/){a=$2}; if (/inet/){b=$2; print a b}}')
-    inet_list="lo:127.0.0.1/8 eth0:10.1.28.211/24 usb0:192.168.1.2/24"
     for item in $inet_list; do
         case $item in
             lo:*|usb0:*)
@@ -201,25 +199,20 @@ write_config()
     echo "netmask.ipV4: $3" >> $ecm_conf
 }
 
-setup_usbmode()
+ecm_enabled()
 {
-    if [ -f $usbmode ]; then
-        cp -f $usbmode $usbmode.bak
-        if ! grep ecm $usbmode; then
-            echo "ecm" >>$usbmode
+    local gadget_mode=/sys/class/android_usb/android0/functions
+
+    if [ -f $gadget_mode ]; then
+        ecm=`cat ${gadget_mode} | sed -e 's/,/\n/g' | egrep -x "e[ce]m"`
+        if [ -z "$ecm" ] ; then
+            return 1
         fi
     else
-        echo "ecm" > $usbmode
+        return 1
     fi
-}
 
-revert_usbmode()
-{
-    if [ -f $usbmode.bak ];then
-        cp -f $usbmode.bak $usbmode
-    else
-        rm -f $usbmode
-    fi
+    return 0
 }
 
 create_conf()
@@ -243,14 +236,19 @@ create_conf()
         shift
     done
 
+    if ! ecm_enabled; then
+        echo "ecm not enabled"
+        return 1
+    fi
+
     if [ -z $targ_addr ]; then
         if [ -f $ecm_conf ]; then
             echo "No target address. Exiting without changes."
             return 1
         else
             echo "No target address. Using defaults."
-            targ_addr="192.168.1.2"
-            host_addr="192.168.1.3"
+            targ_addr="192.168.2.2"
+            host_addr="192.168.2.3"
             mask="255.255.255.0"
         fi
     fi
@@ -266,6 +264,23 @@ create_conf()
     return 0
 }
 
+bringdown_ecm()
+{
+    ifconfig usb0 down
+}
+
+bringup_ecm()
+{
+    local target=$(get_param target.ipV4)
+    local netmask=$(get_param netmask.ipV4)
+
+    if [ -z "$netmask" ]; then
+        netmask=255.255.255.0
+    fi
+
+    ifconfig usb0 $target netmask $netmask up
+}
+
 case $1 in
     show)
         if [ -f $ecm_conf ]; then
@@ -276,28 +291,34 @@ case $1 in
         fi
         ;;
     off)
-        local host=$(get_param host.ipV4)
         unconfig_dhcp
-        revert_usbmode
-        restart_ecm $host >/dev/null
+        bringdown_ecm
         ;;
     on)
         # on requires some arguments else it will do default
         echo ""
         if create_conf $@; then
-            setup_usbmode
             local host=$(get_param host.ipV4)
             config_dhcp $host
-            restart_ecm >/dev/null
-            if [ -f $legato_bringup_ecm ]; then
-                echo bringing up interface
-                $legato_bringup_ecm
-            fi
+            restart_ecm > /dev/null
+            bringup_ecm
         else
             echo "Could not create ecm configuration"
             exit 1
         fi
         ;;
+    default)
+	# configure default ecm parameters, but don't start interface
+	if create_conf ; then
+            local host=$(get_param host.ipV4)
+            config_dhcp $host
+            restart_ecm > /dev/null
+        else
+            echo "Could not create ecm configuration"
+            exit 1
+        fi
+        ;;
+
     -h|--help|*)
         usage
         ;;
