Fix host tool 'fwupdate download' exiting with 1 on target reboot
Adding logs to the fwupdate target tool and fwupdate host tool to better
understand the part of the process that they are in, and once we reached
the last part before the reboot, let the host tool end the command with
exit 0 even though the SSH connection has been interrupted.

Also adding some debounce mechanism to avoid calling le_fwupdate_ConnectService
twice.

Resolves: LE-11944
Change-Id: I7a4137f211a23f568cd0782f3323502258ab1a8a

diff --git a/framework/tools/scripts/fwupdate b/framework/tools/scripts/fwupdate
--- a/framework/tools/scripts/fwupdate
+++ b/framework/tools/scripts/fwupdate
@@ -70,8 +70,25 @@ then
 
     SetTargetIP $3
 
-    cat "$FILE" | SshToTarget "$BIN_PATH/fwupdate $COMMAND -"
-    exit $?
+    CMD_LOG=$(mktemp "/tmp/tmp.fwupdate-XXXXX")
+
+    cat "$FILE" | SshToTarget "$BIN_PATH/fwupdate $COMMAND -" | tee ${CMD_LOG}
+    CMD_RET=${PIPESTATUS[1]}
+
+    if [ $CMD_RET -ne 0 ] && [ "$COMMAND" = "download" ]; then
+        # Command failed, but it might be caused by the SSH connection
+        # being interrupted by the reboot.
+        if grep -q "Installing & Reboot" ${CMD_LOG} \
+            && ! grep -q "Error during installation:" ${CMD_LOG}; then
+            echo "Connection interrupted, target is likely rebooting."
+            # Overriding the return code since we are confident that this is a normal use
+            # case.
+            CMD_RET=0
+        fi
+    fi
+
+    rm -f "$CMD_LOG"
+    exit $CMD_RET
 fi
 
 ExitWithError "Command '$COMMAND' unknown."
