Provide initial support for compiler caches (ccache, ...)
While ninja and make are already providing some assistance when it
comes to not rebuilding what's already built, compilation 'from scratch'
can be quite long and resource intensive.

The idea behind this patch is to use object caches such as ccache or
sccache to save compilation results and reuse them transparently.

ccache would be used by default if it is available, unless explicitly
disabled through USE_CCACHE=0.
For instance:
  USE_CCACHE=0 make wp76xx

Path to the compiler cache can be passed through env variable CCACHE.
For instance, as to use sccache (https://github.com/mozilla/sccache):
  CCACHE=sccache make localhost

Resolves: LE-10248
Change-Id: I28af16a12ebf57073f089435f8b6741098bae1d2

diff --git a/framework/tools/mkTools/ninja-generator b/framework/tools/mkTools/ninja-generator
--- a/framework/tools/mkTools/ninja-generator
+++ b/framework/tools/mkTools/ninja-generator
@@ -35,6 +35,18 @@ else
     COMPILER="g++ -std=c++0x"
 fi
 
+# Use ccache.
+if [[ "$USE_CCACHE" == "1" ]]
+then
+    if [ -z "${CCACHE}" ]
+    then
+        echo "Unable to find ccache while it is enabled."
+        exit 1
+    fi
+
+    COMPILER="${CCACHE} ${COMPILER}"
+fi
+
 echo "Tools arch: $TOOLS_ARCH"
 
 TOOLS_ARCH_FLAGS=""
