Use virt platform for target testing
The idea is to provide a way to package a virt runtime as a Docker
image.
Then it is easy to instanciate a virtual target, run the tests against it
and tear it down without having to manage a real target.

To build the Docker image, you would need to do:
$ make virt
$ cd targetFiles/virt
$ ./build.sh

To run the tests:
DEST_IP=172.17.0.3 TARGET_TYPE=virt ./run-tests target-ut

Resolves: LE-5908 LE-4559 LE-6531 LE-4135
Change-Id: Ib330d10847412a575f48e24216725c089c8cd693

diff --git a/run-tests b/run-tests
--- a/run-tests
+++ b/run-tests
@@ -119,17 +119,19 @@ function CleanBuild()
 
 function TargetIdentify()
 {
-    echo "Identifying target ..."
-    TARGET_MODEL=$(ssh -o ConnectTimeout=5 root@$DEST_IP "bsinfo -l | grep \" - \$(bsinfo -s -t)\" | sed -e 's/BS//' -e 's/ - .*$//'" 2> /dev/null)
-    if [ -z "$TARGET_MODEL" ]; then
-        echo "Unable to determine remote target model"
-        exit 1
-    fi
-
-    TARGET_TYPE=$($SOURCEDIR/bin/gettargettype $TARGET_MODEL)
     if [ -z "$TARGET_TYPE" ]; then
-        echo "Unable to determine remote target type"
-        exit 1
+        echo "Identifying target ..."
+        TARGET_MODEL=$(ssh -o ConnectTimeout=5 -p $TARGET_SSH_PORT  root@$DEST_IP "bsinfo -l | grep \" - \$(bsinfo -s -t)\" | sed -e 's/BS//' -e 's/ - .*$//'" 2> /dev/null)
+        if [ -z "$TARGET_MODEL" ]; then
+            echo "Unable to determine remote target model"
+            exit 1
+        fi
+
+        TARGET_TYPE=$($SOURCEDIR/bin/gettargettype $TARGET_MODEL)
+        if [ -z "$TARGET_TYPE" ]; then
+            echo "Unable to determine remote target type"
+            exit 1
+        fi
     fi
 
     echo "Testing Legato on $DEST_IP (type = $TARGET_TYPE)"
@@ -154,8 +156,8 @@ function TargetUpdateLegato()
 
 function TargetUnitTest()
 {
-    if [ "$DEST_IP" == "" ]; then
-        echo "Target IP address is not available. Unit testing on target will be skipped."
+    if [ -z "$DEST_IP" ]; then
+        echo "Target IP address (DEST_IP) is not available. Unit testing on target will be skipped."
         return
     fi
 
