Remove static liblegato lib from system build
The static liblegato library is currently being bundled into the system.
This is taking unnecessary flash space and should be removed from the system.

Resolves: LE-13168
Change-Id: Ic56a1f81d8b1fb464369d50e46b6a51088ddf4c6

diff --git a/framework/liblegato/ninja-generator b/framework/liblegato/ninja-generator
--- a/framework/liblegato/ninja-generator
+++ b/framework/liblegato/ninja-generator
@@ -30,6 +30,12 @@ then
     exit 1
 fi
 
+if [ -z "$STATIC_LIB_DIR" ]
+then
+    echo "**ERROR: STATIC_LIB_DIR is not set." 1>&2
+    exit 1
+fi
+
 DEBUG_DIR=$BUILD_DIR/../debug
 
 NINJA_SCRIPT=$BUILD_DIR/build.ninja
@@ -111,7 +117,7 @@ fi
 CFLAGS="${CFLAGS} -I${LEGATO_ROOT}/build/${TARGET}/framework/include"
 
 LIBLEGATO_SHARED_NAME=$LIB_DIR/liblegato.so
-LIBLEGATO_STATIC_NAME=$LIB_DIR/liblegato.a
+LIBLEGATO_STATIC_NAME=$STATIC_LIB_DIR/liblegato.a
 
 cat >> $NINJA_SCRIPT <<EOF
 builddir = $BUILD_DIR
