Delete build.ninja if ninja-generator fails.
If creating build.ninja fails, delete the partially built build.ninja
file.

Resolves: LE-12763
Change-Id: I89c71a2929f55f3ec443011303bce03eaaf377f6

diff --git a/framework/liblegato/ninja-generator b/framework/liblegato/ninja-generator
--- a/framework/liblegato/ninja-generator
+++ b/framework/liblegato/ninja-generator
@@ -53,6 +53,9 @@ function ObjectsFromSources()
     done
 }
 
+# On failure, clean out ninja build script
+trap "rm -f $NINJA_SCRIPT" EXIT
+
 # Clean out previous ninja script, put in header
 cat > $NINJA_SCRIPT <<EOF
 # Build script for the Legato application framework's C runtime library (liblegato).
@@ -120,3 +123,5 @@ do
     echo
 
 done >> $NINJA_SCRIPT
+
+trap - EXIT
