Updates to the platform services, target files, and the core makefiles.

diff --git a/targetFiles/shared/bin/appTool b/targetFiles/shared/bin/appTool
--- a/targetFiles/shared/bin/appTool
+++ b/targetFiles/shared/bin/appTool
@@ -9,9 +9,12 @@ APPS_BACKUP_ROOT=$LEGATO_ROOT/appsBackup
 APPS_SYS_CFG_BACKUP=sysCfgBack
 APPS_CFG_BACKUP=cfgBack
 SANDBOX_ROOT=/tmp/legato/sandboxes
+PREINSTALL_SCRIPT_RELATIVE_PATH=script/pre-install
+POSTINSTALL_SCRIPT_RELATIVE_PATH=script/post-install
 
 ACTION=$1
 APP_NAME=$(basename "$2" | sed 's/\.[^.]*$//')
+UNPACKED_APP_DIR_PATH=${3%/}
 
 exitCode=0
 
@@ -34,19 +37,15 @@ fi
 PrintUsage()
 {
     echo
-    echo "USAGE: `basename $0` [start|stop|restart|remove|status|version|info] APP_NAME [ APP_NAME ... ]"
-    echo "   or: `basename $0` [start|stop|restart|remove|status|version|info] '*'"
-    echo "   or: `basename $0` [list|status|info]"
-    echo "   or: `basename $0` install APP_NAME"
+    echo "USAGE: `basename $0` install APP_NAME UNPACKED_APP_DIR_PATH"
+    echo "   or: `basename $0` remove APP_NAME"
+    echo "   or: `basename $0` restore APP_NAME"
     echo
-    echo "In the first form, names of one or more applications are given."
+    echo "In the first form, app will be installed from specified path."
     echo
-    echo "In the second form, all installed applications will be acted upon."
+    echo "In the second form, specified app will be removed."
     echo
-    echo "In the third form, no application names are given."
-    echo
-    echo "In the fourth form, one application name is given and the application file must be"
-    echo "provided on stdin."
+    echo "In the third form, specified app will be restored if any backup is available."
     echo
 }
 
@@ -68,44 +67,6 @@ AppStatus()
     while [ $# -ge 1 ]
     do
         appCtrl "status" "$1"
-
-        if [ $? -ne 0 ]
-        then
-            exit 1
-        fi
-
-        shift
-    done
-}
-
-
-AppInfo()
-{
-    if [ $# -eq 0 ]
-    then
-        appCtrl "info"
-        exit $?
-    fi
-
-    while [ $# -ge 1 ]
-    do
-        appCtrl "info" "$1"
-
-        if [ $? -ne 0 ]
-        then
-            exit 1
-        fi
-
-        shift
-    done
-}
-
-
-AppVersion()
-{
-    while [ $# -ge 1 ]
-    do
-        appCtrl "version" "$1"
 
         if [ $? -ne 0 ]
         then
@@ -162,49 +123,35 @@ StopApp()
 InstallApp()
 # Takes a single application name as its only argument.
 {
-    echo "Installing app '$1'..."
+    appName="$1"
+    unpackedAppDirPath="$2"
+    preInstallScriptPath=$unpackedAppDirPath/$PREINSTALL_SCRIPT_RELATIVE_PATH
 
-    (
-        # Create the directory to install into.
-        mkdir -p "$APPS_ROOT/$1" &&
-
-        # Unpack the app into the app's install directory.
-        if ! which bsdtar > /dev/null 2>&1
-        then
-            tar xj -C "$APPS_ROOT/$1"
-        else
-            bsdtar xjop -f - -C "$APPS_ROOT/$1"
-        fi
-
-    )
-
-    if [ $? -ne 0 ]
+    # Check whether any pre-install script exists. If yes pass it to install-hook.
+    if [ -f "$preInstallScriptPath" ]
     then
-        rm -r "$APPS_ROOT/$1"
-        echo "Failed to unpack the application."
-        return 1
+        echo "Running pre-install script"
+
+        install-hook "$preInstallScriptPath"
+
+        if [ $? -ne 0 ]
+        then
+            echo "***Error: PreInstall script failed"
+            return 1
+        fi
     fi
 
     (
-        # Fix up the permissions.
-        (
-            if ! which bsdtar > /dev/null 2>&1
-            then
-                chown -R root:root "$APPS_ROOT/$1"
-            fi
-        ) &&
-        ( find "$APPS_ROOT/$1" -type d | xargs chmod a+x-ws ) &&
-        ( find "$APPS_ROOT/$1" ! -type d | xargs chmod a-xws ) &&
-        ( chmod -R a+x "$APPS_ROOT/$1/bin" ) &&
-
+        # Move the install directory of the app into the back up directory.
+        ( mv "$unpackedAppDirPath"  "$APPS_ROOT/$appName") &&
         # Install the application's configuration into the root user's configuration tree.
-        ( appCfgInstall "$1" ) &&
+        ( appCfgInstall "$appName" ) &&
 
         # Create a user account for the app.
-        ( appUserAdd "$1" ) &&
+        ( appUserAdd "$appName" ) &&
 
         # Set the permissions for the app.
-        ( appSetFilePermissions "$1" ) &&
+        ( appSetFilePermissions "$appName" ) &&
 
         # Load the latest IPC binding configuration into the Service Directory.
         ( sdir load )
@@ -212,10 +159,26 @@ InstallApp()
 
     if [ $? -ne 0 ]
     then
-        rm -r "$APPS_ROOT/$1"
-        echo "Failed to install the unpacked application"
+        rm -rf "$APPS_ROOT/$appName"
+        echo "FAILED"
         return 1
     else
+        # Check whether any post-install script exists. If yes pass it to install-hook.
+        postInstallScriptPath=$APPS_ROOT/$appName/$POSTINSTALL_SCRIPT_RELATIVE_PATH
+
+        if [ -f "$postInstallScriptPath" ]
+        then
+            echo "Running post-install script"
+
+            install-hook "$postInstallScriptPath"
+
+            if [ $? -ne 0 ]
+            then
+                rm -rf "$APPS_ROOT/$appName"
+                echo "***Error: PostInstall script failed"
+                return 1
+            fi
+        fi
         echo "DONE"
     fi
 }
@@ -374,6 +337,8 @@ RestoreBackupApp()
     then
         echo "FAILED to restore original version of app $appName"
         return 1
+    else
+        echo "DONE"
     fi
 }
 
@@ -418,23 +383,6 @@ fi
 
 case "$ACTION" in
 
-start)
-    CheckAppNameAvail
-    StartApp $APP_LIST
-    ;;
-
-stop)
-    CheckAppNameAvail
-    StopApp $APP_LIST
-    ;;
-
-restart)
-    CheckAppNameAvail
-    StopApp $APP_LIST
-    exitCode=0
-    StartApp $APP_LIST
-    ;;
-
 install)
     CheckAppNameAvail
 
@@ -443,6 +391,19 @@ install)
     then
         echo "***ERROR: One specific application name must be provided for install."
         PrintUsage
+        exit 1
+    fi
+
+    if [ "$UNPACKED_APP_DIR_PATH" = "" ]
+    then
+        echo "***ERROR: Missing app package path."
+        PrintUsage
+        exit 1
+    fi
+
+    if ! [ -d "$UNPACKED_APP_DIR_PATH" ]
+    then
+        echo "***ERROR: Provided wrong app package path: $UNPACKED_APP_DIR_PATH."
         exit 1
     fi
 
@@ -464,7 +425,7 @@ install)
 
     if [[ $appStatus == "not_installed" ]]
     then
-        InstallApp $APP_NAME
+        InstallApp "$APP_NAME" "$UNPACKED_APP_DIR_PATH"
 
         installStatus=$?
 
@@ -514,21 +475,21 @@ remove)
     done
     ;;
 
-status)
-    AppStatus $APP_LIST
-    ;;
-
-version)
+restore)
     CheckAppNameAvail
-    AppVersion $APP_LIST
-    ;;
 
-list)
-    ListApps
-    ;;
+    # Only one, specific application name allowed.
+    if [ "$APP_NAME" = "*" ]
+    then
+        echo "***ERROR: One specific application name must be provided for install."
+        PrintUsage
+        exit 1
+    fi
 
-info)
-    AppInfo $APP_LIST
+    echo "Restoring APP: $APP_NAME"
+    # Now call the restoring the app from backup
+    RestoreBackupApp $APP_NAME
+    exitCode=$?
     ;;
 
 *)
@@ -539,3 +500,5 @@ info)
 esac
 
 exit $exitCode
+
+
diff --git a/targetFiles/shared/bin/legato b/targetFiles/shared/bin/legato
--- a/targetFiles/shared/bin/legato
+++ b/targetFiles/shared/bin/legato
@@ -12,8 +12,8 @@ StopLegatoTimeout=10
 
 ACTION=$1
 
-# Make sure /usr/local/bin is in the path.
-PATH=/usr/local/bin:$PATH
+# Make sure /usr/local/bin and /sbin is in the path.
+PATH=/usr/local/bin:/sbin:$PATH
 
 
 # Check if ps supports arguments.  If so, we need to run "ps aux" to be able
@@ -24,6 +24,15 @@ then
     PS=ps
 fi
 
+# Detect the PCONFIG file. This will disable the positioning service
+if [ -f /mnt/userrw/PCONFIG ]
+then
+    ENABLE_POS=false
+    ENABLE_OLDAV=false
+else
+    ENABLE_POS=true
+    ENABLE_OLDAV=true
+fi
 
 PrintUsage()
 {
@@ -54,6 +63,12 @@ LegatoStatus()
 
 StartLegato()
 {
+    # Provide information about the device model
+    if [ ! -f "/tmp/deviceModel" ]
+    then
+        bsinfo -l | grep ' - '`bsinfo -t | cut -d ' ' -f 4` | sed 's/^BS//;s/ - .*$//' > /tmp/deviceModel
+    fi
+
     # Make sure it isn't running already.
     if IsRunning supervisor
     then
@@ -69,7 +84,7 @@ StartLegato()
     # Configure the Supervisor to start the sysProcs.
     mkdir -p $SUPERVISOR_CONFIG_ROOT &&
     > $SUPERVISOR_CONFIG_ROOT/sysProcs
-    for procName in serviceDirectory logCtrlDaemon configTree watchdog
+    for procName in serviceDirectory logCtrlDaemon configTree watchdog updateDaemon
     do
         if [ ! -f "/usr/local/bin/$procName" ]
         then
@@ -102,8 +117,12 @@ StartLegato()
 
 StopLegato()
 {
+    wasRunning="no"
+
     if IsRunning supervisor
     then
+        wasRunning="yes"
+
         echo "Stopping Legato... "
 
         # Tell the Supervisor to shutdown Legato.
@@ -145,12 +164,24 @@ StopLegato()
     # Make sure the serviceDirectory isn't still running.
     if IsRunning serviceDirectory
     then
+        wasRunning="yes"
+
         echo "Service Directory still running. Killing it now ..."
+
         killall serviceDirectory > /dev/null 2>&1
+
+    fi
+
+    # supervisor mounted smack. supervisor is dead now so unmount smack else it may
+    # give us trouble if we need to unmount the things smack is mounted to
+    umount /opt/legato/smack
+
+    if [ $wasRunning = "yes" ]
+    then
+        echo "DONE."
     else
         echo "Legato wasn't running."
     fi
-    echo "DONE."
 }
 
 
@@ -158,6 +189,143 @@ AddUserToAppBinding()
 {
     config set users/$1/bindings/$2/app        $3
     config set users/root/bindings/$2/interface  $2
+}
+
+# Add binding configuration needed by the framework tools.
+# TODO: Remove this when the tools becomes command-line apps.
+# This should probably read a file created by the build to determine
+# what needs to be bound.
+AddBindings()
+{
+    # cm tool
+    AddUserToAppBinding root le_mdc modemService &&
+    AddUserToAppBinding root le_mrc modemService &&
+    AddUserToAppBinding root le_sim modemService &&
+    AddUserToAppBinding root le_sms modemService &&
+    AddUserToAppBinding root le_temp modemService &&
+    AddUserToAppBinding root le_adc modemService &&
+    AddUserToAppBinding root le_data dataConnectionService
+
+    # fwupdate tool
+    AddUserToAppBinding root le_info modemService &&
+    AddUserToAppBinding root le_fwupdate modemService
+
+    # agent
+    AddUserToAppBinding root le_posCtrl positioningService &&
+    AddUserToAppBinding root le_pos positioningService
+}
+
+StartupScriptMissing()
+{
+    ! ls /mnt/flash/startup/* > /dev/null 2>&1
+}
+
+StartupScriptOld()
+{
+    ! diff /mnt/flash/startup /mnt/flash/startupDefaults > /dev/null 2>&1
+}
+
+CopyDefaultsToStartup()
+{
+    mkdir -p /mnt/flash/startup
+    if ! cp -a /mnt/flash/startupDefaults/* /mnt/flash/startup/
+    then
+        echo "Copying default startup scripts failed"
+        exit 1
+    fi
+    echo "DONE."
+}
+
+BackupOldStartup()
+{
+    rm -rf /mnt/flash/startupBackups
+    if ! mv /mnt/flash/startup /mnt/flash/startupBackups
+    then
+        echo "Backing up old startup scripts failed"
+        exit 1
+    fi
+    echo "DONE."
+}
+
+InstallStartupScripts()
+{
+    echo "STARTUP SCRIPTS MISSING."
+    echo "Installing startup scripts..."
+
+    CopyDefaultsToStartup
+
+}
+
+UpdateStartupScripts()
+{
+    echo "STARTUP SCRIPTS OUT OF DATE."
+    echo "Backing up old startup scripts to /mnt/flash/startupBackups..."
+
+    BackupOldStartup
+
+    echo "Installing new startup scripts..."
+
+    CopyDefaultsToStartup
+}
+
+# Remove functions always assume we are removing from /mnt/flash
+# and never from built in /mnt/legato. /mnt/flash may or may not
+# be blank but we will try to delete anyway.
+RemoveAppUsers()
+{
+    for app in $(ls /mnt/flash/opt/legato/apps)
+    do
+        appName="app$app"
+        /usr/sbin/deluser "$appName"
+        rm -rf "/home/$appName"
+    done
+}
+
+RemoveLegato()
+{
+    echo "Removing old install"
+    RemoveAppUsers
+    rm -rf /mnt/flash/usr/local/*
+    rm -rf /mnt/flash/opt/*
+}
+
+UpdateAndRunApps()
+{
+    # Get the new app list
+    APP_LIST=`ls /usr/local/bin/apps`
+
+    if [ $ENABLE_POS = "false" ]
+    then
+        APP_LIST=$(echo $APP_LIST | sed 's/positioningService\.[^ ]*//')
+        echo "Skipping installation of positioningService due to configuration"
+    fi
+
+    if [ $ENABLE_OLDAV = "false" ]
+    then
+        APP_LIST=$(echo $APP_LIST | sed 's/airvantage\.[^ ]*//')
+        echo "Skipping installation of M3DA airvantage app due to configuration"
+    fi
+
+    # Install new versions of the bundled apps.
+    for appFile in $APP_LIST
+    do
+        APP_NAME=$(basename "$appFile" | sed "s/\.[^.]*$//") &&
+        cat /usr/local/bin/apps/$appFile | /usr/local/bin/app install ""$APP_NAME""
+    done
+
+    # Start the bundled apps.
+    for appFile in $APP_LIST
+    do
+        APP_NAME=$(basename "$appFile" | sed "s/\.[^.]*$//") &&
+        /usr/local/bin/app start $APP_NAME
+    done
+}
+
+InstallApps()
+{
+    AddBindings &&
+
+    UpdateAndRunApps
 }
 
 # This function is run during the boot sequence to see if a new Legato
@@ -169,7 +337,7 @@ BootCheck()
         echo "No legato installed in /mnt/legato"
     fi
 
-    if ! diff /mnt/legato/opt/legato/version /mnt/flash/opt/legato/version > /dev/null
+    if ! diff /mnt/legato/opt/legato/version /mnt/flash/opt/legato/builtInVersion >/dev/null 2>&1
     then
         echo "*** Initializing new Legato version ***"
 
@@ -178,55 +346,28 @@ BootCheck()
         then
             rm -fr /mnt/flash/startupDefaults
         fi
-        cp -R /mnt/legato/mnt/flash/startupDefaults /mnt/flash/startupDefaults
+        cp -a /mnt/legato/mnt/flash/startupDefaults /mnt/flash/
         echo "DONE"
+
+
+        # remove any possible left-over or corrupted legato files in /mnt/flash
+        RemoveLegato
+        # Copy over built in legato to /mnt/flash/
+        cp -a /mnt/legato/opt /mnt/flash/
 
         # Make sure the startup scripts are executable and owned by root.
         chown -R root:root /mnt/flash/startupDefaults &&
         chmod -R u+x /mnt/flash/startupDefaults || exit 1
 
-        # If there are no startup scripts installed yet, install them
-        if ! ls /mnt/flash/startup/* > /dev/null 2>&1
+        if StartupScriptMissing
         then
-            echo "STARTUP SCRIPTS MISSING."
-            echo "Installing startup scripts..."
-
-            mkdir -p /mnt/flash/startup
-            cp -R /mnt/flash/startupDefaults/* /mnt/flash/startup || exit 1
-
-            echo "DONE."
+            InstallStartupScripts
         fi
 
-        # If the startup scripts are out of date, update them
-        if ! diff /mnt/flash/startup /mnt/flash/startupDefaults > /dev/null
+        if StartupScriptOld
         then
-            echo "STARTUP SCRIPTS OUT OF DATE."
-            echo "Backing up old startup scripts to /mnt/flash/startupBackups..."
-
-            rm -rf /mnt/flash/startupBackups
-            mv /mnt/flash/startup /mnt/flash/startupBackups || exit 1
-
-            echo "DONE."
-            echo "Installing new startup scripts..."
-
-            mkdir -p /mnt/flash/startup
-            cp -R /mnt/flash/startupDefaults/* /mnt/flash/startup || exit 1
-
-            echo "DONE."
+            UpdateStartupScripts
         fi
-
-        # Copy over the contents of opt
-        cp -R /mnt/legato/opt /mnt/flash/opt
-
-        # Now we need the bind mounts in place to continue
-        /mnt/flash/startup/fg_00_BindMount
-
-        # Update the ld library cache such that all the new framework libraries under /usr/local/lib
-        # can be found by the dynamic linker.
-        echo "Updating dynamic linker configuration..."
-        umount /etc/ld.so.cache
-        /sbin/ldconfig -v -C /var/run/ld.so.cache &&
-        mount --bind /var/run/ld.so.cache /etc/ld.so.cache
 
         # Finally, touch a file to show that we need to run the post boot sequence
         touch /mnt/flash/startup/postcheck
@@ -242,93 +383,90 @@ PostBootCheck()
         return 0
     fi
 
-    # Add binding configuration needed by the framework tools.
-    # TODO: Remove this when the tools becomes command-line apps.
-    (
-        # cm tool
-        AddUserToAppBinding root le_mdc modemService &&
-        AddUserToAppBinding root le_mrc modemService &&
-        AddUserToAppBinding root le_sim modemService &&
-        AddUserToAppBinding root le_sms modemService &&
-        AddUserToAppBinding root le_data dataConnectionService
-
-        # fwupdate tool
-        AddUserToAppBinding root le_info modemService &&
-        AddUserToAppBinding root le_fwupdate modemService
-
-        # agent
-        AddUserToAppBinding root le_posCtrl positioningService &&
-        AddUserToAppBinding root le_pos positioningService
-    ) &&
-
-    # Install and start the bundled applications.
-    (
-        # Remove old versions of the bundled apps.
-        for appFile in `ls /usr/local/bin/apps`
-        do
-            APP_NAME=$(basename "$appFile" | sed "s/\.[^.]*$//") &&
-            /usr/local/bin/app remove ""$APP_NAME""
-        done
-
-        # Install new versions of the bundled apps.
-        for appFile in `ls /usr/local/bin/apps`
-        do
-            APP_NAME=$(basename "$appFile" | sed "s/\.[^.]*$//") &&
-            cat /usr/local/bin/apps/$appFile | /usr/local/bin/app install ""$APP_NAME""
-        done
-
-        # Start the bundled apps.
-        for appFile in `ls /usr/local/bin/apps`
-        do
-            APP_NAME=$(basename "$appFile" | sed "s/\.[^.]*$//") &&
-            /usr/local/bin/app start $APP_NAME
-        done
-    )
+    InstallApps &&
 
     rm /mnt/flash/startup/postcheck
+
+    # Setup the installed version file
+    cp /mnt/legato/opt/legato/version /mnt/flash/opt/legato/builtInVersion
 }
+
+# To see if it is already bind mounted
+CheckBindMount()
+{
+    local dir_path=$1
+    local mount_on=${2%$1}
+    local mounted_on=$(df $dir_path | grep -v Filesystem | awk '{print $6}')
+    if [ "$mounted_on" = "$mount_on" ]
+    then
+        return 0
+    fi
+    return 1
+}
+
+CreateMountpointsAndBind()
+{
+    local map=$1
+    local as=$2
+    echo "Remapping $map --> $as"
+    mkdir -p $map
+    mkdir -p $as
+    mount --bind $map $as
+}
+
+BindMount()
+{
+    local dir_path=$1
+    local mount_on=$3
+    if CheckBindMount $dir_path $mount_on 2>/dev/null
+    then
+        echo "Already mapped $mount_on --> $dir_path"
+    else
+        if ! mount | grep $ >/dev/null
+        then
+            CreateMountpointsAndBind $mount_on $dir_path
+        else
+            # display current binding
+            echo "$dir_path map needs updating"
+            df $dir_path
+            umount "$dir_path"
+            CreateMountpointsAndBind $mount_on $dir_path
+        fi
+    fi
+}
+
 
 InstallLegato()
 {
+    reboot_advised=""
+
     # Make sure the old version of the framework is shut down.
     StopLegato
 
-    if [ -f /opt/legato/usr/local/bin/legato ]
-    then
-        INSTALL_BASE=/mnt/legato
-        legato_part=true
-    else
-        INSTALL_BASE=/mnt/flash
-        legato_part=false
-    fi
-
     echo "Cleaning..."
 
-    # Remove the old version of the Legato framework.
-    rm -rf /usr/local/*
+    # RemoveLegato really removes what was installed and the next reboot would cause the
+    # built in to be installed but we are installing a new legato so we should recopy the
+    # builtInVersion file which marks this install as superceding the built in.
+    if diff /mnt/legato/opt/legato/version /mnt/flash/opt/legato/builtInVersion >/dev/null 2>&1
+    then
+        RemoveLegato
+        mkdir -p /mnt/flash/opt/legato
+        cp -a /mnt/legato/opt/legato/version /mnt/flash/opt/legato/builtInVersion
+    else
+        RemoveLegato
+    fi
 
     # Remove the old default startup scripts.
-    rm -rf $INSTALL_BASE/startupDefaults
+    rm -rf /mnt/flash/startupDefaults
 
     echo "Checking target environment..."
-    mount | grep ' /usr/local ' > /dev/null
-    if [ $? -ne 0 ]
-    then
-        echo "Remapping /usr/local --> $INSTALL_BASE/usr/local"
-        mkdir -p $INSTALL_BASE/usr/local
-        mkdir -p /usr/local
-        mount --bind $INSTALL_BASE/usr/local   /usr/local
-    fi
+    # make sure all our bind mounts are pointing to the right places
+    BindMount /opt on /mnt/flash/opt
+    BindMount /usr/local on /mnt/flash/usr/local
+    BindMount /home on /mnt/flash/home
 
-    mount | grep ' /opt ' > /dev/null
-    if [ $? -ne 0 ]
-    then
-        # Make /opt actually be /mnt/flash/opt.
-        echo "Remapping /opt --> /mnt/flash/opt"
-        mkdir -p /mnt/flash/opt
-        mkdir -p /opt
-        mount --bind /mnt/flash/opt /opt
-    fi
+    mkdir -p /home/root
 
     echo "Unpacking..."
 
@@ -340,16 +478,12 @@ InstallLegato()
     if ! which bsdtar > /dev/null 2>&1
     then
         tar x &&
-
-        # Make sure everything under /usr and /opt are owned by root and are in the root users group.
-        # TODO: This must be removed when switching to read-only root file system.
-        # This can be removed when we have a better version of tar on target.
+        # Old versions of firmware may have r/w rootfs and busybox tar.
+        echo "The firmware appears to be very old"
+        echo "Probably there will be features that won't work on such old firmware."
         chmod -R go-w /usr/local &&
         chown -R root:root /usr &&
         chown -R root:root /opt &&
-        # Just in case busybox tar set non-root ownership of /
-        # TODO: This must be removed when switching to read-only root file system.
-        # This can be removed when we have a better version of tar on target.
         chown root:root /
     else
         bsdtar xpom -f -
@@ -358,113 +492,41 @@ InstallLegato()
 
     # Make sure the startup scripts are executable and owned by root.
     chown -R root:root /mnt/flash/startupDefaults &&
-    chmod -R u+x /mnt/flash/startupDefaults || exit 1
+    chmod -R u+x /mnt/flash/startupDefaults || exit 1 # This is a very uninformative failure
 
-    # If there are no startup scripts installed yet, we cant continue until the scripts have
-    # been installed and the target has been rebooted.
-    if ! ls /mnt/flash/startup/* > /dev/null 2>&1
+    if StartupScriptMissing
     then
-        echo "STARTUP SCRIPTS MISSING."
-        echo "Installing startup scripts..."
-
-        mkdir -p /mnt/flash/startup
-        cp /mnt/flash/startupDefaults/* /mnt/flash/startup || exit 1
-
-        echo "DONE."
-        echo "**** REBOOT REQUIRED ****"
-        echo "Reboot target and restart legato framework installation process."
-        exit 42
+        InstallStartupScripts
+        reboot_advised="yes"
     fi
 
-    # If the startup scripts are out of date, we cant continue installation until the scripts
-    # have been updated and the target has been rebooted.
-    if ! diff /mnt/flash/startup /mnt/flash/startupDefaults > /dev/null
+    if StartupScriptOld
     then
-        echo "STARTUP SCRIPTS OUT OF DATE."
-        echo "Backing up old startup scripts to /mnt/flash/startupBackups..."
-
-        rm -rf /mnt/flash/startupBackups
-        mv /mnt/flash/startup /mnt/flash/startupBackups || exit 1
-
-        echo "DONE."
-        echo "Installing new startup scripts..."
-
-        mkdir -p /mnt/flash/startup
-        cp /mnt/flash/startupDefaults/* /mnt/flash/startup || exit 1
-
-        echo "DONE."
-        echo "**** REBOOT REQUIRED ****"
-        echo "Reboot target and restart legato framework installation process."
-        exit 42
+        UpdateStartupScripts
+        reboot_advised="yes"
     fi
 
-    # Update the ld library cache such that all the new framework libraries under /usr/local/lib
-    # can be found by the dynamic linker.
-    echo "Updating dynamic linker configuration..."
-    umount /etc/ld.so.cache
-    /sbin/ldconfig -v -C /var/run/ld.so.cache &&
-    mount --bind /var/run/ld.so.cache /etc/ld.so.cache &&
+    # make sure we are really up to date on our bind mounts
+    /mnt/flash/startup/fg_00_BindMount
 
     # Start up the new version of the framework.
     # This script makes sure the supervisor and installer runs with the "admin" SMACK label.
     /mnt/flash/startup/fg_10_StartLegato &&
 
-    # Add binding configuration needed by the framework tools.
-    # TODO: Remove this when the tools becomes command-line apps.
-    (
-        # cm tool
-        AddUserToAppBinding root le_mdc modemService &&
-        AddUserToAppBinding root le_mrc modemService &&
-        AddUserToAppBinding root le_sim modemService &&
-        AddUserToAppBinding root le_sms modemService &&
-        AddUserToAppBinding root le_data dataConnectionService
-
-        # fwupdate tool
-        AddUserToAppBinding root le_info modemService &&
-        AddUserToAppBinding root le_fwupdate modemService
-
-        # agent
-        AddUserToAppBinding root le_posCtrl positioningService &&
-        AddUserToAppBinding root le_pos positioningService
-    ) &&
-
-    # Install and start the bundled applications.
-    (
-        # Remove old versions of the bundled apps.
-        for appFile in `ls /usr/local/bin/apps`
-        do
-            APP_NAME=$(basename "$appFile" | sed "s/\.[^.]*$//") &&
-            /usr/local/bin/app remove ""$APP_NAME""
-        done
-
-        # Install new versions of the bundled apps.
-        for appFile in `ls /usr/local/bin/apps`
-        do
-            APP_NAME=$(basename "$appFile" | sed "s/\.[^.]*$//") &&
-            cat /usr/local/bin/apps/$appFile | /usr/local/bin/app install ""$APP_NAME""
-        done
-
-        # Start the bundled apps.
-        for appFile in `ls /usr/local/bin/apps`
-        do
-            APP_NAME=$(basename "$appFile" | sed "s/\.[^.]*$//") &&
-            /usr/local/bin/app start $APP_NAME
-        done
-    ) &&
+    InstallApps &&
 
     # Remove the app package files for the bundled applications to save space in flash.
-    # Or just copy back the version file if we're in a separate partition
-    if [ "$legato_part" = "true" ]
-    then
-        # Make sure the version file is correct
-        cp /opt/legato/version /mnt/legato/opt/legato/version
-    else
-        rm -rf /usr/local/bin/apps
-    fi
+    rm -rf /usr/local/bin/apps
 
     if [ $? -eq 0 ]
     then
         echo "SUCCESS"
+        if [ "$reboot_advised" = "yes" ]
+        then
+            echo "**** REBOOT ADVISED ****"
+            echo "Startup scripts have changed. A reboot is recommended to avoid possibility of system instability"
+            exit 42
+        fi
     else
         echo "FAILED"
         exit 1
diff --git a/targetFiles/shared/bin/setNet b/targetFiles/shared/bin/setNet
--- a/targetFiles/shared/bin/setNet
+++ b/targetFiles/shared/bin/setNet
@@ -4,81 +4,214 @@
 # static forces macfixed
 # static needs more params - how to handle in a script?
 
+cmd_name=$(basename $0)
+
 usage () {
     echo ""
     echo "Purpose:"
-    echo "$0 allows the user to set up eth0 to re-use the same MAC hardware address"
+    echo "$cmd_name allows the user to set up eth0 to re-use the same MAC hardware address"
     echo "across reboots and to allow simple configuration of a static IPv4 address on eth0"
     echo "If you have a fancy 'interfaces' setup then you probably shouldn't use this script"
-    echo "but your original file will be backed up with a timestamp added to the name."
+    echo "as it makes changes to the /etc/network/interfaces file but your original file will"
+    echo "be backed up with a timestamp added to the name so you can restore it by hand if"
+    echo "necessary."
     echo ""
     echo "Usage:"
-    echo "$0 [macrandom|macfixed] [dhcp|static] [address <address>] [netmask <netmask>] [gateway <gateway>]"
-    echo "if called without arguments or with -h or --help this message will be printed"
-    echo "'static' overrides 'macrandom' to 'macfixed'"
-    echo "'address', 'netmask' and 'gateway', if given, are only used with 'static'"
-    echo "$0 'macrandom' restores the factory default where a different MAC address will be used on each reboot"
+    echo "$cmd_name [macrandom|macfixed] [dhcp|static] [address <address>] [netmask <netmask>] [gateway <gateway>] [nameserver <nameserver>[,<nameserver>...] [mac <mac>]"
+    echo "If called without arguments or with -h or --help this message will be printed"
+    echo "Arguments are optional and where they are missing current values will be used where it"
+    echo "makes sense to do so."
+    echo "e.g. if only an address is given 'static' is assumed and the current netmask, gateway and"
+    echo "nameservers are reused."
+    echo "Some combinations are invalid and will be flagged as errors."
+    echo "e.g. 'static' and 'macrandom' cannot coextist."
+    echo ""
+    echo "$cmd_name 'macrandom' as the sole argument restores the factory default where a different"
+    echo "MAC address will be used on each reboot"
+    echo "Note: nameserver addresses should be separated with commas and without spaces."
     exit 1
+}
+
+exit_error () {
+    echo ""
+    echo "ERROR: $1"
+    usage
+}
+
+up_script=/etc/network/if-up.d/static_resolve_conf
+
+write_ifup_script () {
+cat << 'UP_SCRIPT_DATA' >$up_script
+#! /bin/sh
+
+if [ "$IFACE" = "eth0" ]; then
+ns=$(awk 'BEGIN{ in_eth0=0 } \
+     /iface/{ \
+        if ($2 == "eth0"){ \
+            in_eth0=1; \
+        }else{ \
+            in_eth0=0; \
+        } \
+     } \
+     (in_eth0) && ($0 ~ /nameserver/) { $1=""; print $2}' /etc/network/interfaces)
+
+    echo "" >/etc/resolv.conf
+IFS=','
+for s in $ns; do
+    echo "nameserver $s" >> /etc/resolv.conf
+done
+fi
+UP_SCRIPT_DATA
+chmod a+x $up_script
+}
+
+remove_ifup_script () {
+    rm -rf $up_script 2>/dev/null
+}
+
+get_nameservers () {
+    local l=""
+    local n
+    for n in $(awk '/nameserver/{print $2}' /etc/resolv.conf 2>/dev/null); do
+        if [ -n "$l" ]; then
+            l="$l,$n"
+        else
+            l=$n
+        fi
+    done
+
+    echo $l
+}
+
+get_current_settings () {
+    # find out if we are static/dhcp and if we have a fixed mac
+    # we can use set in a function without messing the arg array $@ outside
+    set -- $(awk 'BEGIN{in_eth0=0} \
+    /iface/{if ($2~/eth0/){in_eth0=1; print $4}else{in_eth0=0}} \
+    (in_eth0){if ($1~/hwaddress/){print $3}}' </etc/network/interfaces)
+
+    netassign=$1
+    mac=$2
+    if [ -n "$mac" ]; then
+        mactype="fixed"
+    else
+        mactype="random"
+    fi
+
+    # get nameservers, obviously 
+    nameserver=$(get_nameservers)
+
+    # get the mac and ipV4 network params we are currently using
+    r=$(route | awk '/eth0/{if  (/UG/){print "gway="$2; quit} }')
+    r="$r $(ifconfig eth0 | awk '/HWaddr/{print "mac="$5}/inet\W/{sub(/addr:/,"addr=",$2);sub(/Mask:/,"mask=",$4);print $2,$4}')"
+
+    for b in $r
+    do
+        eval $b
+    done
+}
+
+show_settings () {
+    echo "$mactype mac $mac"
+    echo "address assignment $netassign"
+    echo "    address: ${addr:-none}"
+    echo "    netmask: ${mask:-none}"
+    echo "    gateway: ${gway:-none}"
+    echo "    nameservers: ${nameserver:-none}"
 }
 
 if [ $# -eq 0 ];then
     usage;
 fi
 
-# defaults to fixed mac w/ dhcp
-mactype="fixed"
-netassign="dhcp"
-
-# get current values for mac, addr, mask, gway
-r=$(route | awk '/eth0/{if  (/UG/){print "gway="$2; quit} }')
-r="$r $(ifconfig eth0 | awk '/HWaddr/{print "mac="$5}/inet\W/{sub(/addr:/,"addr=",$2);sub(/Mask:/,"mask=",$4);print $2,$4}')"
+get_current_settings
 
 if [ "$1" = "show" ]
 then
-    for b in $r
-    do
-        echo $b
-    done
+    show_settings
     exit 0
-else
-    for b in $r
-    do
-        eval $b
-    done
 fi
 
-# override with options
+# get options given by user on command line
 while [ $# -gt 0 ]
 do
     case $1 in
     -h|--help) usage ;;
-    macrandom) mactype="random"; netassign="dhcp";;
-    macfixed) mactype="fixed";;
-    static) netassign="static";;
-    dhcp) netassign="dhcp";;
-    address) shift; addr=$1;;
-    netmask) shift; mask=$1;;
-    gateway) shift; gway=$1;;
+    macrandom) user_mactype_random="random";;
+    macfixed) user_mactype_fixed="fixed";;
+    static) user_netassign_static="static";;
+    dhcp) user_netassign_dhcp="dhcp";;
+    address) shift; user_addr=$1;;
+    netmask) shift; user_mask=$1;;
+    gateway) shift; user_gway=$1;;
+    nameserver) shift; user_nameserver=$1;;
+    mac) shift; user_mac=$1;;
     *) echo "unknown option $1"; usage;;
     esac
     shift
 done
 
-if [ "$netassign" = "static" ]
-then
+# Now merge those values that exist (user input overrides existing) and make appropriate
+# inferences while alerting user to nonesense input.
+
+user_mactype=${user_mactype_fixed-$user_mactype_random}
+user_netassign=${user_netassign_static-$user_netassign_dhcp}
+
+if [ "$user_mactype" = "random" ]; then
+    if [ -n "$user_mactype_fixed" ]; then
+        exit_error "cannot define both random mac and fixed mac"
+    elif [ -n "$user_mac" ]; then
+        exit_error "cannot define both a hardware mac address and macrandom"
+    elif [ -n "$user_netassign_static" ] || [ -n "$user_addr$user_gway$user_mask$user_nameserver" ]; then
+        exit_error "cannot use a random mac with a static ip parameters"
+    fi
+    mactype=$user_mactype
+    netassign="dhcp"
+    addr=""
+    gway=""
+    mask=""
+    nameserver=""
+    mac=""
+elif [ "$user_netassign" = "dhcp" ]; then
+    if [ -n "$user_netassign_static" ]; then
+        exit_error "cannot define both dhcp and static"
+    elif [ -n "$user_addr$user_gway$user_mask$user_nameserver" ]; then
+        exit_error "cannot define both dhcp and static ip parameters"
+    fi
     mactype="fixed"
+    netassign="dhcp"
+    addr=""
+    gway=""
+    mask=""
+    nameserver=""
+    mac=${user_mac-$mac}
+elif [ "$user_netassign" = "static" ] || [ -n "$user_addr$user_gway$user_mask$user_nameserver" ]; then
+    mactype="fixed"
+    netassign="static"
+    addr=${user_addr-$addr}
+    mask=${user_mask-$mask}
+    gway=${user_gway-$gway}
+    nameserver=${user_nameserver-$nameserver}
+    mac=${user_mac-$mac}
+elif [ $user_mactype = "fixed" ]; then
+    if [ -n "$user_addr$user_gway$user_mask$user_nameserver$user_netassign" ]; then
+        echo "Unexpected combination of parameters" >&2
+    fi
+    mactype="fixed"
+    echo "net assign $netassign"
+    netassign=${user_netassign:-$netassign}
+    addr=${user_addr-$addr}
+    mask=${user_mask-$mask}
+    gway=${user_gway-$gway}
+    nameserver=${user_nameserver-$nameserver}
+    mac=${user_mac-$mac}
+else
+# Think that should have covered everything but just incase
+    exit_error "Unable to determine user intent."
 fi
 
-# if static, ask mask, gway, addr
-if [ "$netassign" = "dhcp" ]
-then
-    addr=''
-fi
-
-if [ "$mactype" = "random" ]
-then
-    mac=''
-fi
+echo "Setting the following:"
+show_settings
 
 # modify interfaces file
 ifile="/etc/network/interfaces"
@@ -96,6 +229,8 @@ awk 'function writeStatic (mac, addr, mask, gway) {
         print "\taddress " addr
         print "\tnetmask " mask
         print "\tgateway " gway
+# write nameserver entries
+        print "\tnameserver " nameserver 
     }
     function writeDhcp (mac) {
         print "iface eth0 inet dhcp"
@@ -116,9 +251,18 @@ awk 'function writeStatic (mac, addr, mask, gway) {
     addr=$addr \
     mask=$mask \
     gway=$gway \
+    nameserver=$nameserver \
     "${ifile}_${dstamp}" > "${ifile}"
 
 echo "${ifile} has been updated. Original has been renamed ${ifile}_${dstamp}"
+
+if [ "$netassign" = "static" ]; then
+# create the script that updates the resolv.conf if dhcp is not running
+    write_ifup_script
+else
+    remove_ifup_script
+fi
+
 # if this is being run from an ssh connection ssh would hang if we didn't 
 # disconnect before the network went down
 nohup sh -c "sleep 1; ifdown eth0; ifup eth0" 2>/dev/null &
