Initial commit for 14.07 Beta.

diff --git a/apps/test/framework/configTree/configTest.sh.in b/apps/test/framework/configTree/configTest.sh.in
--- a/apps/test/framework/configTree/configTest.sh.in
+++ b/apps/test/framework/configTree/configTest.sh.in
@@ -1,17 +1,28 @@
 #!/bin/bash
 
 
+# Make sure that the shared libraries are available.
+_script="$(readlink -f ${BASH_SOURCE[0]})"
+_base="$(dirname $_script)"
+
+export LD_LIBRARY_PATH=$_base/../lib
+
+echo "---------------------------------------------------------------------------------------------"
+echo "Lib path: $LD_LIBRARY_PATH"
+echo "---------------------------------------------------------------------------------------------"
+
+
 
 
 # The command line option to look for.  If this text is found that means that the caller wants us to
 # make sure that the required legato system services are running.
 SERVEROPT="withserver"
+SERVER_PARAM=$1
 
 
 
 
-if [ "$1" = "$SERVEROPT" ]
-then
+if [ "$SERVER_PARAM" = "$SERVEROPT" ]; then
     # Make sure that the service directory isn't already running.
     killall serviceDirectory || true
 
@@ -33,16 +44,29 @@ fi
 
 
 
+# When the unit tests are done, this is called to make sure that we don't leave any extra processes
+# running.
+function CleanUp
+{
+    echo "Shutting down configTree unit tests."
 
-function ExecWithTimeout()
+    if [ "$SERVER_PARAM" = "$SERVEROPT" ]; then
+        killall serviceDirectory || true
+    else
+        killall configTree || true
+    fi
+}
+
+
+
+
+function ExecWithTimeout
 {
     # Extract the parameters passed to this funciton.
     TIMEOUT=$1
-    COMMAND=$2
-    COMMAND_ARGS=${*:3}
-
-    # Grab the PID so the
-
+    EXIT_EXPECTED=$2
+    COMMAND=$3
+    COMMAND_ARGS=${*:4}
 
     # Start a timer process, if it isn't stopped before the sleep returns the process will exit our
     # script.  Grab our PID so that the child can kill this script if it times out.
@@ -62,10 +86,17 @@ function ExecWithTimeout()
     $COMMAND $COMMAND_ARGS
     RET_VAL=$?
 
-    echo "SUCCESS.  Killing timeout process $TIMER_PROCID."
+    echo "Subprocess complete, killing timeout process $TIMER_PROCID."
     kill $TIMER_PROCID || true
 
-    return $RET_VAL
+    # Report the exit status of the subprocess, and if required, kill the script.
+    [ $RET_VAL -eq $EXIT_EXPECTED ] && echo "Subprocess had: SUCCEEDED."
+
+    if [ $RET_VAL -ne $EXIT_EXPECTED ]; then
+        echo "Subprocess had: FAILED, with exit code: $RET_VAL"
+        CleanUp
+        exit $RET_VAL
+    fi
 }
 
 
@@ -76,10 +107,20 @@ sleep 1
 @CONFIG_TOOL_BIN@ set /configTest/testCount 0
 
 
+# Set the configTree transaction timeout to something more manageable.
+@CONFIG_TOOL_BIN@ set /configTree/transactionTimeout 5 int
+
+
 # These two executables create and fail to close a read and write transaction respectivly.  If the
 # configTree doesn't handle this situation correctly then things will start hanging.
-ExecWithTimeout 5 @EXECUTABLE_OUTPUT_PATH@/configDropReadExe
-ExecWithTimeout 5 @EXECUTABLE_OUTPUT_PATH@/configDropWriteExe
+ExecWithTimeout 10 0 @EXECUTABLE_OUTPUT_PATH@/configDropReadExe
+ExecWithTimeout 10 0 @EXECUTABLE_OUTPUT_PATH@/configDropWriteExe
+
+
+# Now, tell them to hang around to make sure that the automatic timeouts work.
+ExecWithTimeout 10 1 @EXECUTABLE_OUTPUT_PATH@/configDropReadExe hangAround
+ExecWithTimeout 10 1 @EXECUTABLE_OUTPUT_PATH@/configDropWriteExe hangAround
+
 
 
 # Now, fire up a bunch of instances of the config test executable, all in parallel.  If any of them
@@ -89,12 +130,16 @@ do
     MY_STR+="$i "
 done
 
-echo $MY_STR | ExecWithTimeout 20 xargs -n 1 -P 0 @EXECUTABLE_OUTPUT_PATH@/configTestExe
+echo $MY_STR | ExecWithTimeout 60 0 xargs -n 1 -P 0 @EXECUTABLE_OUTPUT_PATH@/configTestExe
 
 # Report the number of tests that were run.
 echo "Number of tests run:"
 @CONFIG_TOOL_BIN@ get /configTest/testCount
 
 
-# TODO: Get rid of this when configTree is started automaticly for the texting.
-killall configTree || true
+# Now, as a final test and to clean up after ourselves.  Delete the trees from the system.
+ExecWithTimeout 10 0 @EXECUTABLE_OUTPUT_PATH@/configDelete
+
+
+# All, done, so try to shutdown cleanly.
+CleanUp
diff --git a/framework/tools/scripts/configtargetssh b/framework/tools/scripts/configtargetssh
--- a/framework/tools/scripts/configtargetssh
+++ b/framework/tools/scripts/configtargetssh
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+commandName=$(basename $0)
+
 # Generates a key pair, configures the local user's account to use that key to talk to the
 # specified IP address, and installs the public key in that target device's root account's
 # list of authorized keys.
@@ -13,7 +15,24 @@ TARGET_IP=$1
 
 function PrintUsage()
 {
-    echo "Usage: $(basename $0) TARGET_IP_ADDR"
+    echo "NAME"
+    echo "        $commandName - Configure secure shell access to target device."
+    echo
+    echo "SYNOPSYS"
+    echo "        $commandName [TARGET_IP_ADDR]"
+    echo
+    echo "DESCRIPTION"
+    echo "        If the TARGET_IP_ADDR is not provided as an argument, then $commandName"
+    echo "        will try to use the contents of the DEST_IP environment variable."
+    echo
+    echo "        Follow the interactive instructions provided by the tool."
+}
+
+function ExitWithError()
+{
+    echo "***ERROR: $1"
+    echo "Try '$commandName --help' for usage instructions."
+    exit 1
 }
 
 
@@ -27,17 +46,18 @@ fi
 # Did they specify too many arguments?
 if [ $# -gt 1 ]
 then
-    echo "***ERROR: Too many arguments."
-    PrintUsage
-    exit 1
+    ExitWithError "Too many arguments."
 fi
 
 # Make sure they gave us a target IP address.
-if ! [ $TARGET_IP ]
+if ! [ "$TARGET_IP" ]
 then
-    echo "***ERROR: Target IP address not provided."
-    PrintUsage
-    exit 1
+    if ! [ "DEST_IP" ]
+    then
+        ExitWithError "Target IP address not provided."
+    fi
+
+    TARGET_IP=$DEST_IP
 fi
 
 # If there isn't already a key file for Legato targets, create one.
diff --git a/framework/tools/scripts/instapp b/framework/tools/scripts/instapp
--- a/framework/tools/scripts/instapp
+++ b/framework/tools/scripts/instapp
@@ -11,7 +11,7 @@ function PrintUsage()
 }
 
 APP_FILE=$1
-DEST_IP=$2
+TARGET_IP=$2
 
 # Check if they are asking for help.
 if [ "$1" = "-h" -o "$1" = "help" -o "$1" = "--help" ]
@@ -29,20 +29,25 @@ then
 fi
 
 # Check that the second argument is provided and can be pinged.
-if ! [ $DEST_IP ]
+if ! [ $TARGET_IP ]
 then
-    echo "***ERROR: Second argument should be an IP address."
-    PrintUsage
-    exit 1
+    if ! [ $DEST_IP ]
+    then
+        echo "***ERROR: Destination IP address not available."
+        PrintUsage
+        exit 1
+    fi
+
+    TARGET_IP=$DEST_IP
 fi
 
-if ! ping -c 1 -w 1 $DEST_IP > /dev/null
+if ! ping -c 1 -w 1 $TARGET_IP > /dev/null
 then
-    echo "***ERROR: Device address $DEST_IP seems to be unreachable."
+    echo "***ERROR: Device address $TARGET_IP seems to be unreachable."
     exit 1
 fi
 
 # Feed the application file into tar xf running in the application install directory.
 APP_NAME=$(basename "$APP_FILE" | sed 's/\.[^.]*$//')
 echo "Installing application '$APP_NAME' from file '$APP_FILE'."
-cat $APP_FILE | ssh root@$DEST_IP "/usr/local/bin/app install '$APP_NAME'"
+cat $APP_FILE | ssh root@$TARGET_IP "/usr/local/bin/app install '$APP_NAME'"
diff --git a/framework/tools/scripts/instlegato b/framework/tools/scripts/instlegato
--- a/framework/tools/scripts/instlegato
+++ b/framework/tools/scripts/instlegato
@@ -1,8 +1,16 @@
 #!/bin/bash
 
 # This script installs the Legato framework in /usr/local on a target device using SCP.
+# It will also install the startup scripts if they are not present or they are different
+# from the startup scripts in the $LEGATO_ROOT dir on host.
 # Note: this implies that /usr/local must exist and be writeable on the target.
 # The legato framework must have also been built for the appropriate target device.
+
+# Exit codes
+# 0 - Success
+# 1 - General error
+# 42 - Startup files are copied and the target is rebooting.
+
 
 function PrintUsage()
 {
@@ -16,7 +24,7 @@ function PrintUsage()
 }
 
 SRC_DIR=$1
-DEST_IP=$2
+TARGET_IP=$2
 
 # Check if they are asking for help.
 if [ "$1" = "-h" -o "$1" = "help" -o "$1" = "--help" ]
@@ -25,40 +33,166 @@ then
     exit 0
 fi
 
-if [ $# -ne 2 ]
-then
-    echo "***ERROR: Incorrect number of arguments."
-    echo
-    PrintUsage
-    exit 1
-fi
-
 # Check that the first argument exists and is a directory.
+# If not, try sticking "$LEGATO_ROOT/build/" on the front and see if that's a directory.
 if ! [ -d "$SRC_DIR" ]
 then
-    echo "***ERROR: First argument should be a directory."
-    echo "Directory '$SRC_DIR' not found."
-    echo "Perhaps it needs to be built?"
-    echo
-    PrintUsage
-    exit 1
+    SRC_DIR_TRY2="$LEGATO_ROOT/build/$SRC_DIR"
+    if ! [ -d "$SRC_DIR_TRY2" ]
+    then
+        echo "***ERROR: First argument should be a directory."
+        echo "Directory '$SRC_DIR' not found."
+        echo "Perhaps it needs to be built?"
+        echo
+        PrintUsage
+        exit 1
+    else
+        SRC_DIR="$SRC_DIR_TRY2"
+    fi
+fi
+
+# If LEGATO_ROOT is not defined, try to deduce it from the (build) SRC_DIR
+if [ -z "$LEGATO_ROOT" ]
+then
+    LEGATO_ROOT="$SRC_DIR/../.."
+    if ! [ -f "$LEGATO_ROOT/version" ] || ! [ -f "$LEGATO_ROOT/README.md" ]
+    then
+        echo "***ERROR: Unable to find LEGATO_ROOT."
+        echo "Please declare LEGATO_ROOT as your Legato source directory,"
+        echo "or use bin/legs."
+        echo
+        PrintUsage
+        exit 1
+    fi
 fi
 
 # Check that the second argument is provided and can be pinged.
-if ! [ $DEST_IP ]
+if ! [ $TARGET_IP ]
 then
-    echo "***ERROR: Second argument should be an IP address."
+    if ! [ $DEST_IP ]
+    then
+        echo "***ERROR: Destination IP address not available."
+        PrintUsage
+        exit 1
+    fi
+
+    TARGET_IP=$DEST_IP
+fi
+
+if ! ping -c 1 -w 1 $TARGET_IP > /dev/null
+then
+    echo "***ERROR: Device address $TARGET_IP seems to be unreachable."
     echo
-    PrintUsage
     exit 1
 fi
 
-if ! ping -c 1 -w 1 $DEST_IP > /dev/null
-then
-    echo "***ERROR: Device address $DEST_IP seems to be unreachable."
-    echo
-    exit 1
-fi
+function UpdateStartupFiles()
+{
+    reboot_pending=0
+    targetName=$1
+    target_md5sum=$2
+
+    case $targetName in
+    swi-mdm9x15)
+        srcpath=$LEGATO_ROOT/targetFiles/mdm-9x15
+        dstpath=root@$TARGET_IP:/mnt/flash/startup
+        ;;
+    *)
+        echo "Attempting to install legato on unrecognized target '$targetName'"
+        echo "This script will not be able to set up start up scripts on this platform."
+        echo "It is your responsibility to make sure the environment is configured correctly"
+        echo "to run legato."
+        return
+        ;;
+    esac
+
+    md5sum=($(cat $srcpath/startup/* | md5sum))
+    if [[ $# -eq 1 ]]
+    then
+        # There are no startup scripts. Copy them over
+        echo "Copying startup scripts to target"
+        scp $srcpath/startup/* $dstpath
+        if [[ $? != 0 ]]
+        then
+            echo "Copying failed. Check target."
+            exit 1
+        fi
+        reboot_pending=1
+    elif ! [[ $target_md5sum == ${md5sum[0]} ]]
+    then
+        # Startup scripts on target differ from host version.
+        # Over write with new files, and make a backup of the ones on target.
+        echo "Startup scripts have changed. Backing up old startup scripts to host."
+        if [[ -d $srcpath/backup ]]
+        then
+            timestamp=$(date +%F_%T)
+            tar -cjf  $srcpath/backup_$timestamp.bz2 -C $srcpath backup
+            rm $srcpath/backup/*
+        else
+            mkdir -p $srcpath/backup
+        fi
+        scp $dstpath/* $srcpath/backup/
+        if [[ $? != 0 ]]
+        then
+            echo "Backup of old startup scripts failed. Check target."
+            exit 1
+        fi
+        ssh root@$TARGET_IP 'rm /mnt/flash/startup/*'
+        echo "Copying new startup scripts to target"
+        scp $srcpath/startup/* $dstpath
+        if [[ $? != 0 ]]
+        then
+            echo "Copying failed. Check target."
+            exit 1
+        fi
+        echo "Old startup scripts from target are in $srcpath/backup/"
+        reboot_pending=1
+    else
+        echo "Startup scripts are up to date."
+    fi
+
+    if [[ $reboot_pending > 0 ]]
+    then
+        echo "Startup scripts have been updated and the target will reboot."
+        echo "Wait until the target has rebooted then execute this script again"
+        echo "to finish installing legato"
+        if ! ssh root@$TARGET_IP '/sbin/reboot >/dev/null &'
+        then
+            echo "Error while attempting to reboot target"
+            exit 1
+        else
+            # 42 is a semi-arbitrary value chosen as an exit code unlikely to occur in nature.
+            # It indicates that the target has new startup files copied to it and is now rebooting.
+            # If we are run by jenkins-build then the test script will wait and re-run
+            # instlegato if it receives this exit code.
+            exit 42
+        fi
+    fi
+}
+
+# Check for startup scripts
+echo "Checking startup scripts ..."
+result=$(ssh root@$TARGET_IP '
+    name=$(uname -n)
+    if [[ $name == "swi-mdm9x15" ]]
+    then
+        sfpath="/mnt/flash/startup"
+        if ! [ -d $sfpath ]
+        then
+            mkdir -p $sfpath
+        fi
+        cd $sfpath
+        if [ $(ls | wc -l) -ne 0 ]
+        then
+            local_md5sum=$(cat * 2> /dev/null | md5sum)
+        fi
+    fi
+
+    echo "$name $local_md5sum"
+    ')
+
+UpdateStartupFiles $result
+
 
 TAR_FILE="$SRC_DIR/legato-runtime.tar"
 
@@ -72,22 +206,46 @@ then
     exit 1
 fi
 
-# Create a tarball of the target device's staging area and stream it into place on the device.
-# NOTE: If we don't sleep for a second, the ssh server on the target will kill the legato
-# runtime when the ssh session terminates.
+# 1. Stop the framework on target, if it is installed and running.
+# 2. Stream the tarball of the target device's staging area into place on the device.
+# 3. Update the ld.so.cache on target, so the Legato libs can be found by the dynamic linker/loader.
+# 4. Start the framework on target.
+# 5. Install and start the bundled applications.
+# 6. Remove the app package files for the bundled applications to save space in flash.
 cat "$TAR_FILE" |
-ssh root@$DEST_IP '
+# NOTE: If the content of the script being sent to the target ssh shell is too long, it will
+#       reject it with a horrible, unclear error message.
+ssh root@$TARGET_IP '
     if [ -f /usr/local/bin/legato ]
     then
         /usr/local/bin/legato stop
     fi
+    rm -rf /usr/local/*
     mkdir -p /usr/local/bin &&
     cd / &&
     tar x &&
     chmod -R go-w /usr/local &&
-    chown -R root:root /usr/local &&
+    chown -R root:root /usr &&
+    chown -R root:root /opt &&
+    chown root:root / &&
     ( umount /etc/ld.so.cache || true ) &&
     /sbin/ldconfig -v -C /var/run/ld.so.cache &&
     mount --bind /var/run/ld.so.cache /etc/ld.so.cache &&
-    sleep 2' &&
+    /usr/local/bin/legato start &&
+    (
+        for appFile in `ls /usr/local/bin/apps`
+        do
+            APP_NAME=$(basename "$appFile" | sed "s/\.[^.]*$//") &&
+            cat /usr/local/bin/apps/$appFile | /usr/local/bin/app install ""$APP_NAME""
+        done
+        for appFile in `ls /usr/local/bin/apps`
+        do
+            APP_NAME=$(basename "$appFile" | sed "s/\.[^.]*$//") &&
+            /usr/local/bin/app start $APP_NAME
+        done
+    )
+    rm -rf /usr/local/bin/apps
+    ' &&
+
 echo "DONE."
+
diff --git a/framework/tools/scripts/lsapp b/framework/tools/scripts/lsapp
--- a/framework/tools/scripts/lsapp
+++ b/framework/tools/scripts/lsapp
@@ -2,13 +2,14 @@
 
 function PrintUsage()
 {
-    echo "USAGE: $(basename $0) DEST_IP"
+    echo "USAGE: $(basename $0) [DEST_IP]"
     echo
-    echo "  where, DEST_IP = the IP address of the target device."
+    echo "  where, DEST_IP = the IP address of the target device.  If DEST_IP is an available"
+    echo "  environment variable it does not need to be passed in the command-line."
     echo
 }
 
-DEST_IP=$1
+TARGET_IP=$1
 
 # Check if they are asking for help.
 if [ "$1" = "-h" -o "$1" = "help" -o "$1" = "--help" ]
@@ -18,19 +19,24 @@ then
 fi
 
 # Check that the first argument is provided and can be pinged.
-if ! [ $DEST_IP ]
+if ! [ $TARGET_IP ]
 then
-    echo "***ERROR: Argument should be an IP address."
-    PrintUsage
-    exit 1
+    if ! [ $DEST_IP ]
+    then
+        echo "***ERROR: Destination IP address not available."
+        PrintUsage
+        exit 1
+    fi
+
+    TARGET_IP=$DEST_IP
 fi
 
-if ! ping -c 1 -w 1 $DEST_IP > /dev/null
+if ! ping -c 1 -w 1 $TARGET_IP > /dev/null
 then
-    echo "***ERROR: Device address $DEST_IP seems to be unreachable."
+    echo "***ERROR: Device address $TARGET_IP seems to be unreachable."
     exit 1
 fi
-
 
 # List the contents of the application install directory.
-ssh root@$DEST_IP ls /opt/legato/apps
+ssh root@$TARGET_IP "/usr/local/bin/app list"
+
diff --git a/targetFiles/shared/bin/app b/targetFiles/shared/bin/app
--- a/targetFiles/shared/bin/app
+++ b/targetFiles/shared/bin/app
@@ -6,9 +6,12 @@ APPS_ROOT=/opt/legato/apps
 SANDBOX_ROOT=/tmp/legato/sandboxes
 
 ACTION=$1
-APP_NAME=$2
+APP_NAME=$(basename "$2" | sed 's/\.[^.]*$//')
 
 exitCode=0
+
+# used to carry the result of GetAppStatus
+appStatus="unknown"
 
 
 # Make sure /usr/local/bin is in the path.
@@ -18,25 +21,64 @@ export PATH=/usr/local/bin:$PATH
 PrintUsage()
 {
     echo
-    echo "USAGE: `basename $0` [start|stop|restart|remove] APP_NAME [ APP_NAME ... ]"
-    echo "   or: `basename $0` [start|stop|restart|remove] '*'"
+    echo "USAGE: `basename $0` [start|stop|restart|remove|status|version] APP_NAME [ APP_NAME ... ]"
+    echo "   or: `basename $0` [start|stop|restart|remove|status|version] '*'"
+    echo "   or: `basename $0` [list|status]"
     echo "   or: `basename $0` install APP_NAME"
     echo
     echo "In the first form, names of one or more applications are given."
     echo
     echo "In the second form, all installed applications will be acted upon."
     echo
-    echo "In the third form, one application name is given and the application file must be"
+    echo "In the third form, no application names are given."
+    echo
+    echo "In the fourth form, one application name is given and the application file must be"
     echo "provided on stdin."
     echo
 }
 
 
-IsAppInstalled()
-# Takes a single application name as its only argument.
+ListApps()
 {
-    # An app is considered "installed" if an install directory exists for it.
-    test -d "$APPS_ROOT/$1"
+    appCtrl "list"
+}
+
+
+AppStatus()
+{
+    if [ $# -eq 0 ]
+    then
+        appCtrl "status"
+        exit $?
+    fi
+
+    while [ $# -ge 1 ]
+    do
+        appCtrl "status" "$1"
+
+        if [ $? -ne 0 ]
+        then
+            exit 1
+        fi
+
+        shift
+    done
+}
+
+
+AppVersion()
+{
+    while [ $# -ge 1 ]
+    do
+        appCtrl "version" "$1"
+
+        if [ $? -ne 0 ]
+        then
+            exit 1
+        fi
+
+        shift
+    done
 }
 
 
@@ -47,7 +89,7 @@ StartApp()
     do
         echo "Starting app '$1'..."
 
-        appCtrl "start" "$1" 2> /dev/null
+        appCtrl "start" "$1"
 
         if [ $? -ne 0 ]
         then
@@ -68,7 +110,7 @@ StopApp()
     do
         echo "Stopping app '$1'..."
 
-        appCtrl "stop" "$1"  2> /dev/null
+        appCtrl "stop" "$1"
 
         if [ $? -ne 0 ]
         then
@@ -107,10 +149,16 @@ InstallApp()
         ( chown -R root:root "$APPS_ROOT/$1" ) &&
         ( find "$APPS_ROOT/$1" -type d | xargs chmod a+x-ws ) &&
         ( find "$APPS_ROOT/$1" ! -type d | xargs chmod a-xws ) &&
-        ( find "$APPS_ROOT/$1/bin" ! -type d | xargs chmod a+x ) &&
+        ( chmod -R a+x "$APPS_ROOT/$1/bin" ) &&
 
         # Install the application's configuration into the root user's configuration tree.
-        ( appCfgInstall "$1" )
+        ( appCfgInstall "$1" ) &&
+
+        # Create a user account for the app.
+        ( appUserAdd "$1" ) &&
+
+        # Load the latest IPC binding configuration into the Service Directory.
+        ( sdir load )
     )
 
     if [ $? -ne 0 ]
@@ -139,21 +187,74 @@ RemoveApp()
             echo "Couldn't remove installation directory."
         fi
 
-        # Even if it doesn't look like it's installed, delete its configuration anyway,
-        # in case an earlier removal process was interrupted or someone manually deleted
-        # the app's install directory.
+        # In case an earlier removal process was interrupted or someone manually deleted
+        # the app's install directory, even if it doesn't look like it's installed,
+        # delete the app's configuration and user account.
         appCfgRemove "$1"
-
         if [ $? -ne 0 ]
         then
             exitCode=1
             echo "Couldn't remove configuration data."
         fi
 
+        appUserRemove "$1"
+        if [ $? -ne 0 ]
+        then
+            exitCode=1
+            echo "Couldn't remove user account."
+        fi
+
+
+        # Load the latest IPC binding configuration into the Service Directory.
+        sdir load
+        if [ $? -ne 0 ]
+        then
+            exitCode=1
+            echo "Couldn't update Service Directory's IPC bindings."
+        fi
+
         shift
     done
 }
 
+# Before we do any work, see if the framework is running.
+ps | grep supervisor | grep -v grep > /dev/null
+if [ $? -ne 0 ]
+then
+    echo "The legato framework is not running. Please start it before proceeding."
+    exit 1
+fi
+
+# Use the new appCtrl status to determine what state the app is currently in.
+# Sets appStatus top 'not_installed' 'stopped' 'running' or 'unknown'
+GetAppStatus()
+{
+    case $(appCtrl "status" "$1") in
+
+    *installed*)
+        appStatus='not_installed'
+        ;;
+    *stopped*)
+        appStatus='stopped'
+        ;;
+    *running*)
+        appStatus='running'
+        ;;
+    *)
+        appStatus='unknown'
+        ;;
+    esac
+}
+
+# Check that something was given as an app name.
+CheckAppNameAvail()
+{
+    if [ "$APP_NAME" = "" ]
+    then
+        echo "Missing application name."
+        exit 1
+    fi
+}
 
 
 # Check if they are asking for help.
@@ -161,13 +262,6 @@ if [ "$1" = "-h" -o "$1" = "help" -o "$1" = "--help" ]
 then
     PrintUsage
     exit 0
-fi
-
-# Check that something was given as an app name.
-if [ "$APP_NAME" = "" ]
-then
-    echo "Missing application name."
-    exit 1
 fi
 
 # Check that the application root directory exists.
@@ -180,7 +274,7 @@ fi
 APP_LIST=
 if [ "$APP_NAME" = "*" ]
 then
-    APP_LIST=`ls $APPS_ROOT`
+    APP_LIST=`appCtrl list`
     if [ "$APP_LIST" = "" ]
     then
         echo "There are no applications currently installed."
@@ -188,26 +282,35 @@ then
     fi
 else
     shift
-    APP_LIST="$*"
+
+    for arg in "$@"
+    do
+        APP_LIST="$APP_LIST $(basename $arg | sed 's/\.[^.]*$//')"
+    done
 fi
 
 case "$ACTION" in
 
 start)
+    CheckAppNameAvail
     StartApp $APP_LIST
     ;;
 
 stop)
+    CheckAppNameAvail
     StopApp $APP_LIST
     ;;
 
 restart)
+    CheckAppNameAvail
     StopApp $APP_LIST
     exitCode=0
     StartApp $APP_LIST
     ;;
 
 install)
+    CheckAppNameAvail
+
     # Only one, specific application name allowed.
     if [ "$APP_NAME" = "*" ]
     then
@@ -217,18 +320,72 @@ install)
     fi
 
     # In case it's already installed, stop it and remove it first.
-    StopApp $APP_NAME
-    RemoveApp $APP_NAME
-    exitCode=0
+    GetAppStatus $APP_NAME
 
-    # Then install it.
-    InstallApp $APP_NAME
+    if [[ $appStatus == "running" ]]
+    then
+        StopApp $APP_NAME
+        appStatus='stopped'
+    fi
+
+    if [[ $appStatus == "stopped" ]]
+    then
+        RemoveApp $APP_NAME
+        appStatus='not_installed'
+    fi
+
+    if [[ $appStatus == "not_installed" ]]
+    then
+        InstallApp $APP_NAME
+    else
+        echo "Install $APP_NAME failed. Unknown error."
+        # in the future we may use different return codes for different errors
+        exitCode=1
+    fi
+
     ;;
 
 remove)
-    StopApp $APP_LIST
-    exitCode=0
-    RemoveApp $APP_LIST
+    CheckAppNameAvail
+
+    # loop through the list giving each app individual treatment
+    # preserve any non-zero exit code
+    for APP_NAME in $APP_LIST
+    do
+        GetAppStatus $APP_NAME
+
+        if [[ $appStatus == "running" ]]
+        then
+            StopApp $APP_NAME
+            appStatus='stopped'
+        fi
+
+        if [[ $appStatus == "stopped" ]]
+        then
+            RemoveApp $APP_NAME
+        elif [[ $appStatus == "not_installed" ]]
+        then
+            echo "$APP_NAME is not installed. Cannot remove"
+            exitCode=1
+        else
+            echo "Remove $APP_NAME failed. Unknown error."
+            # in the future we may use different return codes for different errors
+            exitCode=1
+        fi
+    done
+    ;;
+
+status)
+    AppStatus $APP_LIST
+    ;;
+
+version)
+    CheckAppNameAvail
+    AppVersion $APP_LIST
+    ;;
+
+list)
+    ListApps
     ;;
 
 *)
