Fix system build when a binary signed app is included
MkTool isn't picking the right binary signed app while building
IMA signed system. Fixed mkTool to recognize signed binary app
while building signed system. Fixed building signed binary app to
include adef and api files. Also added relevant unit test.

Resolves: LE-9674
Change-Id: I0d344557dc855bfc56afea9bbafee4627cba7c77

diff --git a/apps/test/framework/mk/bin-app/Makefile b/apps/test/framework/mk/bin-app/Makefile
--- a/apps/test/framework/mk/bin-app/Makefile
+++ b/apps/test/framework/mk/bin-app/Makefile
@@ -25,6 +25,24 @@ $(TARGET): source.$(TARGET) binary.$(TARGET)
 	    echo "error: source and binary systems differ" >&2; \
 	    exit 1; \
 	fi
+	if [ $(ENABLE_IMA) -eq 1 ] ; then \
+		if ! diff -q $(BUILD_DIR)/source/hello-system.$(TARGET).signed.update \
+		             $(BUILD_DIR)/binary/hello-system.$(TARGET).signed.update; then \
+		    src_system_dir=`mktemp -d`; \
+		    bin_system_dir=`mktemp -d`; \
+		    tar -xjvf $(BUILD_DIR)/build-source/hello-system.signed.$(TARGET) -C $$src_system_dir; \
+		    tar -xjvf $(BUILD_DIR)/build-binary/hello-system.signed.$(TARGET) -C $$bin_system_dir; \
+		    diff -r -U2 "$$src_system_dir" "$$bin_system_dir"; \
+		    src_app_dir=`mktemp -d`; \
+		    bin_app_dir=`mktemp -d`; \
+		    tar -xjvf $(BUILD_DIR)/build-source/app/hello/hello.$(TARGET).signed -C $$src_app_dir; \
+		    tar -xjvf $(BUILD_DIR)/build-binary/app/hello/hello.$(TARGET).signed -C $$bin_app_dir; \
+		    diff -r -U2 "$$src_app_dir" "$$bin_app_dir"; \
+		    rm -rf $$src_system_dir $$bin_system_dir $$src_app_dir $$bin_app_dir; \
+		    echo "error: source and binary signed systems differ" >&2; \
+		    exit 1; \
+	fi; \
+	fi
 	# Providing a 'build' symlink as to keep sources at the same place where they have been
 	# built, otherwise klocwork complains about missing files.
 	ln -sf build-source $(BUILD_DIR)/build
@@ -42,6 +60,14 @@ binary.$(TARGET): app.$(TARGET)
 	    mksys hello-system.sdef -t $(TARGET) -i $(LEGATO_ROOT)/interfaces/modemServices \
 	        -w $(BUILD_DIR)/build -o $(BUILD_DIR)/binary
 	rm -rf $(BUILD_DIR)/build-binary && mv $(BUILD_DIR)/build $(BUILD_DIR)/build-binary
+	#Check if IMA build is enabled, if yes then try to build with signed binary app.
+	if [ $(ENABLE_IMA) -eq 1 ] ; then \
+		rm -rf $(BUILD_DIR)/build; \
+		HELLO_APP=$(BUILD_DIR)/app/hello.$(TARGET).signed.app \
+			mksys hello-system.sdef -t $(TARGET) -i $(LEGATO_ROOT)/interfaces/modemServices \
+				-w $(BUILD_DIR)/build -o $(BUILD_DIR)/binary && \
+		rm -rf $(BUILD_DIR)/build-binary && mv $(BUILD_DIR)/build $(BUILD_DIR)/build-binary; \
+	fi
 
 app.$(TARGET):
 	rm -rf $(BUILD_DIR)/build
