Improve bin-app test case
Ensure test case checks a system built with the source app is identical
to one built with the binary app.

Resolves: LE-7755
Change-Id: Ie63ef4df1e77316b6b4dc906372869798699009d

diff --git a/apps/test/framework/mk/bin-app/Makefile b/apps/test/framework/mk/bin-app/Makefile
--- a/apps/test/framework/mk/bin-app/Makefile
+++ b/apps/test/framework/mk/bin-app/Makefile
@@ -1,6 +1,47 @@
 
 include ../common.mk
 
-$(TARGET):
-	mkapp hello.adef -b -t $(TARGET) -i $(LEGATO_ROOT)/interfaces/modemServices
-	mksys hello-system.sdef -t $(TARGET) -i $(LEGATO_ROOT)/interfaces/modemServices
+.NOTPARALLEL:
+.PHONY: $(TARGET) source.$(TARGET) binary.$(TARGET) app.$(TARGET)
+
+SHELL := /bin/bash
+
+# Use same system, same system name for both source and binary build as GCC embeds file names
+# into generated binaries.
+$(TARGET): source.$(TARGET) binary.$(TARGET)
+	if ! diff -q $(BUILD_DIR)/source/hello-system.$(TARGET).update \
+	             $(BUILD_DIR)/binary/hello-system.$(TARGET).update; then \
+	    src_system_dir=`mktemp -d`; \
+	    bin_system_dir=`mktemp -d`; \
+	    tar -xjvf $(BUILD_DIR)/build-source/hello-system.$(TARGET) -C $$src_system_dir; \
+	    tar -xjvf $(BUILD_DIR)/build-binary/hello-system.$(TARGET) -C $$bin_system_dir; \
+	    diff -r -U2 "$$src_system_dir" "$$bin_system_dir"; \
+	    src_app_dir=`mktemp -d`; \
+	    bin_app_dir=`mktemp -d`; \
+	    tar -xjvf $(BUILD_DIR)/build-source/app/hello/hello.$(TARGET) -C $$src_app_dir; \
+	    tar -xjvf $(BUILD_DIR)/build-binary/app/hello/hello.$(TARGET) -C $$bin_app_dir; \
+	    diff -r -U2 "$$src_app_dir" "$$bin_app_dir"; \
+	    rm -rf $$src_system_dir $$bin_system_dir $$src_app_dir $$bin_app_dir; \
+	    echo "error: source and binary systems differ" >&2; \
+	    exit 1; \
+	fi
+
+source.$(TARGET):
+	rm -rf $(BUILD_DIR)/build
+	HELLO_APP=hello.adef \
+	    mksys hello-system.sdef -t $(TARGET) -i $(LEGATO_ROOT)/interfaces/modemServices \
+	        -w $(BUILD_DIR)/build -o $(BUILD_DIR)/source
+	rm -rf $(BUILD_DIR)/build-source && mv $(BUILD_DIR)/build $(BUILD_DIR)/build-source
+
+binary.$(TARGET): app.$(TARGET)
+	rm -rf $(BUILD_DIR)/build
+	HELLO_APP=$(BUILD_DIR)/app/hello.$(TARGET).app \
+	    mksys hello-system.sdef -t $(TARGET) -i $(LEGATO_ROOT)/interfaces/modemServices \
+	        -w $(BUILD_DIR)/build -o $(BUILD_DIR)/binary
+	rm -rf $(BUILD_DIR)/build-binary && mv $(BUILD_DIR)/build $(BUILD_DIR)/build-binary
+
+app.$(TARGET):
+	rm -rf $(BUILD_DIR)/build
+	mkapp hello.adef -b -t $(TARGET) -i $(LEGATO_ROOT)/interfaces/modemServices \
+	        -w $(BUILD_DIR)/build -o $(BUILD_DIR)/app
+	rm -rf $(BUILD_DIR)/build-app && mv $(BUILD_DIR)/build $(BUILD_DIR)/build-app
