Update toolchain determination
Toolchain determination was not very flexible because it
could only be controlled by X_TOOLCHAIN_DIR and X_TOOLCHAIN_PREFIX
environment variables, with the added kludge of looking at the
USE_CLANG env var when building for localhost.

Also, toolchain determination was pretty much completely
undocumented.

The toolchain determination has been moved to the start-up process
of all of the mk tools, and the details are now stored in the
BuildParams_t object. It can also be controlled using CC,
CXX, LD, AR, AS, STRIP, OBJCOPY, READELF variables, or preferably
by X_CC, X_CXX, X_LD, etc (where X is the target ID, like WP85 or
wp85).  LEGATO_SYSROOT and X_SYSROOT can also be used.

The X_TOOLCHAIN_DIR and X_TOOLCHAIN_PREFIX variables are also
still supported and will be used if one of the other variables
is not set. x_TOOLCHAIN_DIR and x_TOOLCHAIN_PREFIX support
has also been added.

The documentation has been updated (written) for all this.
A few other minor doc fixes were also made in related pages.

The splitdebug script run by the mk tools was modified to
use the STRIP, READELF and OBJCOPY env vars instead of
TOOLCHAIN_DIR and TOOLCHAIN_PREFIX and the targetDefs
make script was modified to export STRIP, READELF and OBJCOPY
for use by mkexe/splitdebug when building the framework.

It was also noticed that error checking was missing from
part of splitdebug.  This was corrected.

Resolves: LE-7574
Change-Id: I6f0b3852d446e0b0c6306f8206a9a09b67977e6d

diff --git a/framework/c/src/ninja-generator b/framework/c/src/ninja-generator
--- a/framework/c/src/ninja-generator
+++ b/framework/c/src/ninja-generator
@@ -18,9 +18,9 @@ then
     exit 1
 fi
 
-if [ -z "$TARGET_CC" ]
+if [ -z "$CC" ]
 then
-    echo "**ERROR: TARGET_CC is not set." 1>&2
+    echo "**ERROR: CC is not set." 1>&2
     exit 1
 fi
 
@@ -33,7 +33,7 @@ fi
 
 if [ ! -z "$TARGET_SYSROOT" ]
 then
-    TARGET_CC="$TARGET_CC --sysroot=$TARGET_SYSROOT"
+    CC="$CC --sysroot=$TARGET_SYSROOT"
 fi
 
 # enable coverage.flags
@@ -98,7 +98,7 @@ builddir = $BUILD_DIR
 rule Compile
   description = Compiling liblegato source file
   depfile = \$out.d
-  command = $TARGET_CC -MMD -MF \$out.d -g -c \$in -o \$out -Wall -fPIC -Werror \$flags \$
+  command = $CC -MMD -MF \$out.d -g -c \$in -o \$out -Wall -fPIC -Werror \$flags \$
             -DLE_COMPONENT_NAME=framework \$
             -I$LEGATO_ROOT/framework/c/inc \$
             -DDISABLE_SMACK=$DISABLE_SMACK \$
@@ -108,7 +108,7 @@ rule Compile
 
 rule Link
   description = Linking liblegato
-  command = $TARGET_CC -shared -g -Wl,--build-id -o \$out \$in -lpthread -lrt -ldl $NINJA_LDFLAGS \$
+  command = $CC -shared -g -Wl,--build-id -o \$out \$in -lpthread -lrt -ldl $NINJA_LDFLAGS \$
             && $LEGATO_ROOT/framework/tools/scripts/splitdebug -d $DEBUG_DIR \$out
 
 build $LIBLEGATO : Link $LIBLEGATO_OBJECTS
diff --git a/framework/tools/scripts/splitdebug b/framework/tools/scripts/splitdebug
--- a/framework/tools/scripts/splitdebug
+++ b/framework/tools/scripts/splitdebug
@@ -29,9 +29,13 @@ if [[ $# != 1 ]]; then
     exit 1
 fi
 
-PATH="${TOOLCHAIN_DIR}:${PATH}"
+BUILD_ID=$(${READELF} -n $1|sed 's/    Build ID: //;t;d')
+if [ $? -ne 0 -o -z "$BUILD_ID" ]
+then
+    echo "Failed to extract build ID from '$1'" >&2
+    exit 1
+fi
 
-BUILD_ID=$(${TOOLCHAIN_PREFIX}readelf -n $1|sed 's/    Build ID: //;t;d')
 mkdir -p $DEBUG_DIR/.build-id/${BUILD_ID:0:2}
-${TOOLCHAIN_PREFIX}objcopy --only-keep-debug $1 $DEBUG_DIR/.build-id/${BUILD_ID:0:2}/${BUILD_ID:2}.debug
-${TOOLCHAIN_PREFIX}strip --strip-unneeded $1
+${OBJCOPY} --only-keep-debug $1 $DEBUG_DIR/.build-id/${BUILD_ID:0:2}/${BUILD_ID:2}.debug
+${STRIP} --strip-unneeded $1
